import { DESIGN_AI_TOOLS, TOOL } from "../chapter-end/catalog";
import {
  numberedEndMatter,
  type ChapterEndMatterData,
} from "../chapter-end/types";

const sections = numberedEndMatter(1, 8);

export const ch1EndMatter: ChapterEndMatterData = {
  chapter: 1,
  references: {
    ...sections.references,
    lead: "The names below are the ones this chapter actually introduced — the Web's history, the HTML you used to prototype screens, the Next.js App Router, and the GitHub and Vercel delivery steps. Each linked term opens the in-book term page for the official site. Explainer videos on those pages are optional reference.",
    items: [
      "internet",
      "arpa",
      "dod",
      "arpanet",
      "tcp-ip",
      "world-wide-web",
      "sir-tim-berners-lee",
      "cern",
      "url",
      "http",
      "worldwideweb",
      "html",
      "xml",
      "dom",
      "cgi",
      "php",
      "javascript",
      "netscape",
      "typescript",
      "api",
      "mongodb",
      "react",
      "spa",
      "next-js",
      "ssr",
      "ssg",
      "github",
      "vercel",
      "lms",
      "css",
      "chrome-devtools",
      "node-js",
      "npm",
      "npx",
      "mvn",
      "maven",
      "pip",
      "rest",
      "lts",
      "integrated-development-environment-ide",
      "visual-studio-code",
      "cursor",
      "eslint",
      "prettier",
      "react-developer-tools",
      "git",
      "claude",
      "anthropic",
      "claude-code",
      "tailwind-css",
      "turbopack",
      "google-chrome",
      "jsx",
      "app-router",
    ],
    topics: [
      "HTML headings, paragraphs, lists, tables, images, and forms",
      "Props and children for reusable React components",
      "App Router pages, layouts, and anchor navigation",
      "Git commits, remotes, and personal access tokens",
      "Deploying a Next.js app and turning off Deployment Protection",
    ],
  },
  tools: {
    ...sections.tools,
    lead: "Bookmark these official sites and download pages. You used them to install the runtime, create the Next.js application, inspect pages in the browser, commit the project, and put it on the public Web.",
    items: [
      TOOL.node,
      TOOL.npm,
      TOOL.vscode,
      TOOL.cursor,
      TOOL.chrome,
      TOOL.devtools,
      TOOL.git,
      TOOL.github,
      TOOL.next,
      TOOL.react,
      TOOL.vercel,
    ],
  },
  aiTools: {
    ...sections.aiTools,
    lead: "While the screens are still plain HTML, these AI and design tools are useful for exploring layouts, icons, and prompts before you write every tag by hand.",
    items: DESIGN_AI_TOOLS,
  },
};
