import type { QuizQuestion } from "./types";

export const CH5_LAB_QUESTIONS: QuizQuestion[] = [
  {
    id: "5-sibling",
    section: "5.1.3",
    kind: "concept",
    prompt: "Where should webdev-server live relative to webdev-client?",
    choices: [
      { id: "a", text: "Inside app/ so Next.js can bundle Express" },
      {
        id: "b",
        text: "As a sibling directory (same parent) — not inside the Next.js project tree",
      },
      { id: "c", text: "Inside node_modules" },
      { id: "d", text: "Only on Render, never locally" },
    ],
    answer: "b",
    explanation:
      "The PDF is explicit: the Node project is a sibling of the Next.js app, not nested inside it.",
  },
  {
    id: "5-express-listen",
    section: "5.1.5",
    kind: "syntax",
    prompt: "Which call starts the Express server on port 4000?",
    choices: [
      { id: "a", text: "app.listen(4000)" },
      { id: "b", text: "next start --port 4000" },
      { id: "c", text: "export async function GET()" },
      { id: "d", text: "res.send(4000)" },
    ],
    answer: "a",
    explanation: "app.listen binds the Express process. Route Handlers do not call listen.",
  },
  {
    id: "5-es6-type",
    section: "5.1.7",
    kind: "syntax",
    prompt: "What package.json field lets index.js use import instead of require?",
    choices: [
      { id: "a", text: "\"module\": \"commonjs\"" },
      { id: "b", text: "\"type\": \"module\"" },
      { id: "c", text: "\"jsx\": \"react\"" },
      { id: "d", text: "\"private\": true" },
    ],
    answer: "b",
    explanation: "\"type\": \"module\" turns on ESM so import express from \"express\" works.",
  },
  {
    id: "5-env-name",
    section: "5.2.1",
    kind: "syntax",
    prompt: "Which env var holds the Express origin for the React client?",
    choices: [
      { id: "a", text: "MONGO_URI" },
      { id: "b", text: "NEXT_PUBLIC_HTTP_SERVER" },
      { id: "c", text: "Vercel_URL" },
      { id: "d", text: "SESSION_SECRET" },
    ],
    answer: "b",
    explanation:
      "NEXT_PUBLIC_HTTP_SERVER is inlined into the browser bundle. Locally http://localhost:4000; on Vercel the Render URL.",
  },
  {
    id: "5-send-string",
    section: "5.2.2.1",
    kind: "concept",
    prompt: "Why does PathParameters call sum.toString() before res.send?",
    choices: [
      { id: "a", text: "Express cannot send JSON" },
      {
        id: "b",
        text: "A bare number is treated as an HTTP status code",
      },
      { id: "c", text: "toString enables CORS" },
      { id: "d", text: "Path parameters are already numbers" },
    ],
    answer: "b",
    explanation: "res.send(6) looks like status 6. Send the sum as a string.",
  },
  {
    id: "5-cors",
    section: "5.2.5",
    kind: "concept",
    prompt: "Why does axios from localhost:3000 to localhost:4000 need CORS?",
    choices: [
      { id: "a", text: "Express cannot parse JSON without CORS" },
      {
        id: "b",
        text: "Different ports are different origins; the browser hides the response without Access-Control-Allow-Origin",
      },
      { id: "c", text: "Same-origin Route Handlers also require the cors package" },
      { id: "d", text: "CORS replaces HTTP methods" },
    ],
    answer: "b",
    explanation: "3000 and 4000 are different origins. app.use(cors()) must run before the routes.",
  },
  {
    id: "5-create-order",
    section: "5.2.4",
    kind: "concept",
    prompt: "Why register GET /lab5/todos/create before GET /lab5/todos/:id?",
    choices: [
      { id: "a", text: "POST cannot come first" },
      {
        id: "b",
        text: "Otherwise :id would capture the literal string \"create\"",
      },
      { id: "c", text: "Nodemon requires that order" },
      { id: "d", text: "create is a query parameter" },
    ],
    answer: "b",
    explanation: "Static path segments must be declared before parameterized ones.",
  },
  {
    id: "5-axios-post",
    section: "5.2.6",
    kind: "snippet",
    prompt: "Which call creates a todo with a JSON body?",
    code: `axios.???(\`\${TODOS_API}\`, todo)`,
    choices: [
      { id: "a", text: "get" },
      { id: "b", text: "post" },
      { id: "c", text: "listen" },
      { id: "d", text: "use" },
    ],
    answer: "b",
    explanation: "POST carries the new object in the body after express.json().",
  },
  {
    id: "5-route-handler",
    section: "5.3",
    kind: "syntax",
    prompt: "Which file serves GET /api/lab5/hello inside the Next.js app?",
    choices: [
      { id: "a", text: "webdev-server/Hello.js" },
      { id: "b", text: "app/api/lab5/hello/route.ts" },
      { id: "c", text: "app/labs/lab5/hello.ts" },
      { id: "d", text: "pages/api/hello.js" },
    ],
    answer: "b",
    explanation:
      "Route Handlers are a section of this chapter, not the spine. The folder path under app/api is the URL.",
  },
  {
    id: "5-credentials",
    section: "5.4.3",
    kind: "concept",
    prompt: "How does axios send the Express session cookie?",
    choices: [
      { id: "a", text: "It always does" },
      { id: "b", text: "axios.create({ withCredentials: true })" },
      { id: "c", text: "res.send(cookie)" },
      { id: "d", text: "NEXT_PUBLIC_HTTP_SERVER=cookie" },
    ],
    answer: "b",
    explanation: "Default axios omits cookies. withCredentials: true is required for signin/profile.",
  },
  {
    id: "5-no-mongo",
    section: "5.6",
    kind: "concept",
    prompt: "Where does this chapter store courses and todos?",
    choices: [
      { id: "a", text: "MongoDB Atlas collections created here" },
      { id: "b", text: "In-memory arrays (and JS copies of the JSON files) on the Express process" },
      { id: "c", text: "Only in localStorage" },
      { id: "d", text: "Only in Zustand" },
    ],
    answer: "b",
    explanation: "No MongoDB in Chapter 5. Restarting Node reseeds the arrays. Chapter 6 adds the database.",
  },
  {
    id: "5-render-env",
    section: "5.5.3",
    kind: "concept",
    prompt: "On Vercel, NEXT_PUBLIC_HTTP_SERVER should be…",
    choices: [
      { id: "a", text: "http://localhost:4000" },
      { id: "b", text: "The Render origin with https:// and no trailing slash" },
      { id: "c", text: "The GitHub repository URL" },
      { id: "d", text: "A MongoDB connection string" },
    ],
    answer: "b",
    explanation: "Production UI calls the deployed Express host. Local .env.development stays on port 4000.",
  },
  {
    id: "5-deliverable-branch",
    section: "5.7",
    kind: "concept",
    prompt: "What branch name do both repositories use for this chapter?",
    choices: [
      { id: "a", text: "main only" },
      { id: "b", text: "a5" },
      { id: "c", text: "a4" },
      { id: "d", text: "render" },
    ],
    answer: "b",
    explanation: "Deliverables: a5 on webdev-client and on webdev-server, plus Vercel and Render URLs.",
  },
];
