import type { QuizQuestion } from "./types";

export const CH6_LAB_QUESTIONS: QuizQuestion[] = [
  {
    id: "6-nosql",
    section: "6.1",
    kind: "concept",
    prompt: "What is the biggest structural difference between a MongoDB document and a typical SQL row?",
    choices: [
      { id: "a", text: "Documents cannot store strings" },
      {
        id: "b",
        text: "Document fields can be nested objects and arrays; SQL columns are usually primitives",
      },
      { id: "c", text: "MongoDB requires a schema before the first insert" },
      { id: "d", text: "SQL rows are JSON and documents are CSV" },
    ],
    answer: "b",
    explanation:
      "Collections hold JSON-shaped documents. Relational columns are typically primitives; schema lives in the database. MongoDB leaves shape to the application (and Mongoose).",
  },
  {
    id: "6-compass-uri",
    section: "6.1.2",
    kind: "syntax",
    prompt: "What connection string does Compass use for a local mongod?",
    choices: [
      { id: "a", text: "http://localhost:4000" },
      { id: "b", text: "mongodb://127.0.0.1:27017" },
      { id: "c", text: "NEXT_PUBLIC_HTTP_SERVER" },
      { id: "d", text: "postgres://localhost/kambaz" },
    ],
    answer: "b",
    explanation: "mongod listens on 27017. Compass's New Connection dialog defaults to mongodb://127.0.0.1:27017.",
  },
  {
    id: "6-db-name",
    section: "6.1.3",
    kind: "syntax",
    prompt: "What database and first collection does this chapter create in Compass?",
    choices: [
      { id: "a", text: "kambaz / users" },
      { id: "b", text: "test / todos" },
      { id: "c", text: "next / app" },
      { id: "d", text: "admin / system" },
    ],
    answer: "a",
    explanation: "Create database kambaz with first collection users, then import the JSON files.",
  },
  {
    id: "6-connect",
    section: "6.2.1",
    kind: "snippet",
    prompt: "Which call opens the kambaz database from Node?",
    code: `mongoose.???(CONNECTION_STRING)`,
    choices: [
      { id: "a", text: "listen" },
      { id: "b", text: "connect" },
      { id: "c", text: "find" },
      { id: "d", text: "create" },
    ],
    answer: "b",
    explanation: "mongoose.connect(CONNECTION_STRING) establishes the driver connection.",
  },
  {
    id: "6-env",
    section: "6.2.2",
    kind: "syntax",
    prompt: "Which env var holds the Mongo URI on Express (PDF name)?",
    choices: [
      { id: "a", text: "NEXT_PUBLIC_HTTP_SERVER" },
      { id: "b", text: "DATABASE_CONNECTION_STRING" },
      { id: "c", text: "SESSION_SECRET" },
      { id: "d", text: "CLIENT_URL" },
    ],
    answer: "b",
    explanation:
      "DATABASE_CONNECTION_STRING is the PDF name. This repo also accepts MONGO_CONNECTION_STRING. Unset → in-memory DAOs.",
  },
  {
    id: "6-schema-unique",
    section: "6.2.3",
    kind: "concept",
    prompt: "In the users schema, username is required and unique. What does unique prevent?",
    choices: [
      { id: "a", text: "Empty passwords" },
      { id: "b", text: "Two documents with the same username" },
      { id: "c", text: "Nested modules" },
      { id: "d", text: "Atlas IP allow lists" },
    ],
    answer: "b",
    explanation: "Mongoose/Mongo reject a second insert with the same username.",
  },
  {
    id: "6-model",
    section: "6.2.4",
    kind: "syntax",
    prompt: "How do you build a Mongoose model from a schema?",
    choices: [
      { id: "a", text: "mongoose.model(\"UserModel\", schema)" },
      { id: "b", text: "app.listen(schema)" },
      { id: "c", text: "axios.get(schema)" },
      { id: "d", text: "useState(schema)" },
    ],
    answer: "a",
    explanation: "mongoose.model registers the collection API. The name UserModel is what other schemas ref.",
  },
  {
    id: "6-async",
    section: "6.2.6.1",
    kind: "concept",
    prompt: "Why do user routes become async after the DAO uses Mongoose?",
    choices: [
      { id: "a", text: "Express forbids sync functions" },
      {
        id: "b",
        text: "Model methods return promises; await them before res.json",
      },
      { id: "c", text: "async enables CORS" },
      { id: "d", text: "Compass requires async" },
    ],
    answer: "b",
    explanation: "In-memory Chapter 5 DAOs were sync. Database I/O is async.",
  },
  {
    id: "6-find-predicate",
    section: "6.2.6.3",
    kind: "snippet",
    prompt: "Which call loads only FACULTY users?",
    code: `model.find(???)`,
    choices: [
      { id: "a", text: "{ role: \"FACULTY\" }" },
      { id: "b", text: "\"FACULTY\"" },
      { id: "c", text: "findById(\"FACULTY\")" },
      { id: "d", text: "populate(\"FACULTY\")" },
    ],
    answer: "a",
    explanation: "find({ role }) pattern-matches documents. find() with no argument returns all.",
  },
  {
    id: "6-regex",
    section: "6.2.6.3",
    kind: "concept",
    prompt: "What does new RegExp(partialName, \"i\") do in findUsersByPartialName?",
    choices: [
      { id: "a", text: "Hashes the password" },
      {
        id: "b",
        text: "Case-insensitive substring match on firstName or lastName",
      },
      { id: "c", text: "Creates a unique index" },
      { id: "d", text: "Connects to Atlas" },
    ],
    answer: "b",
    explanation: "The i flag ignores case. $or matches either name field.",
  },
  {
    id: "6-create-id",
    section: "6.2.6.7",
    kind: "concept",
    prompt: "Why assign _id: uuidv4() before model.create(user)?",
    choices: [
      { id: "a", text: "MongoDB cannot generate ids" },
      {
        id: "b",
        text: "We keep string primary keys compatible with earlier JSON; a leftover client _id can break the insert",
      },
      { id: "c", text: "uuidv4 enables sessions" },
      { id: "d", text: "create() requires a Date" },
    ],
    answer: "b",
    explanation: "The PDF warns that an incoming _id can interfere. Generate a fresh string id.",
  },
  {
    id: "6-atlas-path",
    section: "6.3.1.2",
    kind: "concept",
    prompt: "What must the Atlas URI include between the last / and the ?",
    choices: [
      { id: "a", text: "The Vercel project name" },
      { id: "b", text: "The database name kambaz" },
      { id: "c", text: "PORT=4000" },
      { id: "d", text: "use client" },
    ],
    answer: "b",
    explanation:
      "...mongodb.net/kambaz?retryWrites=true. Without the name, the driver does not open the kambaz database.",
  },
  {
    id: "6-one-to-many",
    section: "6.4.2",
    kind: "concept",
    prompt: "Which relationship is course → modules?",
    choices: [
      { id: "a", text: "Many-to-many only" },
      { id: "b", text: "One-to-many (one course, many modules)" },
      { id: "c", text: "One-to-one" },
      { id: "d", text: "No relationship" },
    ],
    answer: "b",
    explanation: "Each course owns many modules. Store a course foreign key, an id array, or embed the modules.",
  },
  {
    id: "6-populate",
    section: "6.4.3.2",
    kind: "concept",
    prompt: "What does populate(\"course\") do on an enrollment query?",
    choices: [
      { id: "a", text: "Deletes the course" },
      {
        id: "b",
        text: "Replaces the stored course id with the course document from the courses collection",
      },
      { id: "c", text: "Creates a SQL JOIN table" },
      { id: "d", text: "Starts Fast Refresh" },
    ],
    answer: "b",
    explanation: "ref: \"CourseModel\" plus populate loads the related document. Then map to unwrap enrollment.course.",
  },
  {
    id: "6-branch",
    section: "6.5",
    kind: "concept",
    prompt: "What branch name do both repositories use for this chapter?",
    choices: [
      { id: "a", text: "a5" },
      { id: "b", text: "a6" },
      { id: "c", text: "main only" },
      { id: "d", text: "atlas" },
    ],
    answer: "b",
    explanation: "Deliverables: a6 on web-dev-client and web-dev-server, plus a new Render service and Vercel preview.",
  },
];
