import type { LectureSlide } from "../types";

export const CHATGPT_TEXT_SLIDES: LectureSlide[] = [
  {
    id: "title",
    title: "Text generation and prompting",
    kind: "title",
    bullets: [
      "Instructions · **roles** · structured JSON",
    ],
  },
  {
    id: "prompting",
    title: "Text generation and prompting",
    kind: "content",
    bullets: [
      "Use an LLM to generate text from a **prompt**, as in ChatGPT",
      "Code, equations, structured **JSON**, or human-like prose",
    ],
  },
  {
    id: "hello-again",
    title: "Text generation and prompting",
    kind: "demo",
    bullets: ["Same **`responses.create`** as Hello World"],
    code: `import OpenAI from "openai";
const client = new OpenAI();

const response = await client.responses.create({
  model: "gpt-4o",
  input: "Write a one-sentence bedtime story about a unicorn.",
});

console.log(response.output_text);`,
    codeLanguage: "javascript",
    codeFile: "webdev-server/openai/hello.js",
  },
  {
    id: "sample",
    title: "Sample Response",
    kind: "demo",
    bullets: [
      "SDKs expose **`output_text`** — all text outputs in one string",
      "Structured data in JSON is **Structured Outputs**",
    ],
    code: `[{
  "id": "msg_67b73f697ba4819183a15cc17d011509",
  "type": "message",
  "role": "assistant",
  "content": [{
    "type": "output_text",
    "text": "In a meadow where moonbeams danced...",
    "annotations": []
  }]
}]`,
    codeLanguage: "json",
    codeHighlightLines: [4, 6],
  },
  {
    id: "instructions",
    title: "Message roles and instruction following",
    kind: "content",
    bullets: [
      "`instructions` gives **high-level** tone, goals, and examples",
      "Those instructions take **priority** over `input`",
    ],
  },
  {
    id: "pirate",
    title: "Talk like a pirate",
    kind: "demo",
    bullets: ["**`instructions`** is the system policy for this request"],
    code: `const response = await client.responses.create({
  model: "gpt-4o",
  instructions: "Talk like a pirate.",
  input: "Are semicolons optional in JavaScript?",
});
console.log(response.output_text);`,
    codeLanguage: "javascript",
    codeFile: "webdev-server/openai/text/instructions.js",
    codeAddedLines: [3],
  },
  {
    id: "roles-code",
    title: "Roles",
    kind: "demo",
    bullets: [
      "The pirate example is the same as a **`developer`** message",
    ],
    code: `const response = await client.responses.create({
  model: "gpt-4o",
  input: [
    { role: "developer", content: "Talk like a pirate." },
    { role: "user", content: "Are semicolons optional in JavaScript?" },
  ],
});`,
    codeLanguage: "javascript",
    codeFile: "webdev-server/openai/text/roles.js",
    codeHighlightLines: [4],
    diagram: "openai-roles-flow",
  },
  {
    id: "roles",
    title: "Roles",
    kind: "content",
    bullets: [
      "**developer** — instructions from the application, weighted **ahead** of user",
      "**user** — instructions from an end user",
      "**assistant** — messages generated by the model",
      "A multi-turn conversation may mix several of these types",
    ],
  },
  {
    id: "choose-model",
    title: "Choosing a model",
    kind: "content",
    bullets: [
      "**Reasoning** models plan multi-step tasks — slower, more expensive",
      "Large vs **mini**: intelligence vs speed and cost",
      "When in doubt, **`gpt-4o`** is a solid mix",
    ],
  },
  {
    id: "prompt-eng",
    title: "Prompt engineering",
    kind: "content",
    bullets: [
      "Be **detailed** to eliminate ambiguity",
      "Provide **examples** of the inputs and outputs you want",
      "On a reasoning model, describe **goals**, not step-by-step instructions",
    ],
  },
  {
    id: "vision",
    title: "Images and vision",
    kind: "demo",
    bullets: [
      "Vision: images as input — a **URL** or a **Base64** data URL",
    ],
    code: `const response = await client.responses.create({
  model: "gpt-4o-mini",
  input: [{
    role: "user",
    content: [
      { type: "input_text", text: "what's in this image?" },
      { type: "input_image", image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Gfp-wisconsin-madison-the-nature-boardwalk.jpg/2560px-Gfp-wisconsin-madison-the-nature-boardwalk.jpg" },
    ],
  }],
});`,
    codeLanguage: "javascript",
    codeFile: "webdev-server/openai/images/url.js",
    codeAddedLines: [[6, 7]],
  },
  {
    id: "detail",
    title: "Specify image input detail level",
    kind: "content",
    bullets: [
      "`detail`: **`low`**, **`high`**, or **`auto`**",
      "`low` is **512×512** and about **85 tokens** — faster, cheaper",
      "`high` adds **170-token** tiles for finer crops",
    ],
  },
  {
    id: "image-gen",
    title: "Image generation",
    kind: "demo",
    bullets: [
      "Jose’s deck used **DALL·E 3**. Current API: **`gpt-image-1`**",
    ],
    code: `const response = await client.images.generate({
  model: "gpt-image-1",
  prompt: "a white siamese cat",
  n: 1,
  size: "1024x1024",
});
console.log(response.data[0].url);`,
    codeLanguage: "javascript",
    codeFile: "webdev-server/openai/images/generate.js",
    codeAddedLines: [[1, 6]],
  },
  {
    id: "tts",
    title: "Text to speech",
    kind: "demo",
    bullets: [
      "`fs` is **server-only** — never import it from a client component",
    ],
    code: `import fs from "fs";
import path from "path";

const mp3 = await client.audio.speech.create({
  model: "gpt-4o-mini-tts",
  voice: "coral",
  input: "Today is a wonderful day to build something people love!",
  instructions: "Speak in a cheerful and positive tone.",
});
const buffer = Buffer.from(await mp3.arrayBuffer());
await fs.promises.writeFile(path.resolve("./speech.mp3"), buffer);`,
    codeLanguage: "javascript",
    codeFile: "webdev-server/openai/audio/tts.js",
    codeAddedLines: [1, [4, 9]],
  },
  {
    id: "stt",
    title: "Speech to text",
    kind: "demo",
    bullets: [
      "`createReadStream` stays on **Express**",
      "Jose also showed **`whisper-1`**. Current: **`gpt-4o-transcribe`**",
    ],
    code: `import fs from "fs";

const transcription = await client.audio.transcriptions.create({
  file: fs.createReadStream("./openai/audio/wonderful.mp3"),
  model: "gpt-4o-transcribe",
});
console.log(transcription.text);`,
    codeLanguage: "javascript",
    codeFile: "webdev-server/openai/audio/stt.js",
    codeAddedLines: [[3, 6]],
  },
  {
    id: "conversation",
    title: "Manually manage conversation state",
    kind: "demo",
    bullets: [
      "The API is **stateless** — you resend the transcript",
    ],
    code: `const history = [{ role: "user", content: "tell me a joke" }];
const completion = await client.responses.create({
  model: "gpt-4o-mini",
  input: history,
});
history.push({ role: "assistant", content: completion.output_text });
history.push({ role: "user", content: "tell me another" });`,
    codeLanguage: "javascript",
    codeFile: "webdev-server/openai/conversation/push.js",
    codeAddedLines: [6, 7],
  },
  {
    id: "structured",
    title: "Structured Outputs",
    kind: "content",
    bullets: [
      "Responses **adhere** to your JSON Schema",
      "**Reliable type-safety**. Explicit refusals. Simpler prompting",
    ],
  },
  {
    id: "zod",
    title: "Structured request",
    kind: "demo",
    bullets: [
      "`responses.parse` plus **`zodTextFormat`** locks the JSON",
      "Jose’s deck used `beta.chat.completions.parse` — same idea, current SDK",
    ],
    code: `import { z } from "zod";
import { zodTextFormat } from "openai/helpers/zod";

const CalendarEvent = z.object({
  name: z.string(),
  date: z.string(),
  participants: z.array(z.string()),
});

const response = await client.responses.parse({
  model: "gpt-4o",
  input: [
    { role: "system", content: "Extract the event information." },
    { role: "user", content: "Alice and Bob are going to a science fair on Friday." },
  ],
  text: { format: zodTextFormat(CalendarEvent, "event") },
});
console.log(response.output_parsed);`,
    codeLanguage: "javascript",
    codeFile: "webdev-server/openai/json/event.js",
    codeAddedLines: [1, 2, [4, 8], 16, 18],
  },
  {
    id: "cot",
    title: "Chain of thought",
    kind: "demo",
    bullets: [
      "Ask for **steps** in the schema; return only `final_answer` to the UI",
    ],
    code: `const Step = z.object({ explanation: z.string(), output: z.string() });
const MathReasoning = z.object({
  steps: z.array(Step),
  final_answer: z.string(),
});

const response = await client.responses.parse({
  model: "gpt-4o",
  input: [{ role: "user", content: "how can I solve 8x + 7 = -23" }],
  text: { format: zodTextFormat(MathReasoning, "math_reasoning") },
});`,
    codeLanguage: "javascript",
    codeFile: "webdev-server/openai/json/chain.js",
    codeAddedLines: [1, [2, 5], 10],
  },
  {
    id: "extract",
    title: "Structured data extraction",
    kind: "demo",
    bullets: ["Same parse pattern — **schema first**, then `output_parsed`"],
    code: `const ResearchPaperExtraction = z.object({
  title: z.string(),
  authors: z.array(z.string()),
  abstract: z.string(),
  keywords: z.array(z.string()),
});`,
    codeLanguage: "javascript",
    codeFile: "webdev-server/openai/json/extract.js",
  },
  {
    id: "ui-schema",
    title: "UI generation",
    kind: "demo",
    bullets: ["**`z.lazy`** lets a node nest children of the same type"],
    code: `const UI = z.lazy(() =>
  z.object({
    type: z.enum(["div", "button", "header", "section", "field", "form"]),
    label: z.string(),
    children: z.array(UI),
    attributes: z.array(z.object({ name: z.string(), value: z.string() })),
  }),
);`,
    codeLanguage: "javascript",
    codeFile: "webdev-server/openai/json/ui.js",
  },
  {
    id: "moderation",
    title: "Content moderation",
    kind: "demo",
    bullets: [
      "Jose parsed a **compliance** schema. Current API: **`moderations.create`**",
    ],
    code: `const moderation = await client.moderations.create({
  model: "omni-moderation-latest",
  input: userText,
});
if (moderation.results[0].flagged) {
  throw new Error("Prompt failed moderation");
}`,
    codeLanguage: "javascript",
    codeFile: "webdev-server/openai/json/moderate.js",
    codeAddedLines: [[1, 4], [5, 7]],
  },
];
