import type { LectureSlide } from "../types";

export const CREATING_A_NEXTJS_REACT_APPLICATION_SLIDES: LectureSlide[] = [
  {
    id: "title",
    title: "Creating a Next.js React application",
    kind: "title",
    bullets: [
      "CS 4550 / CS 5610 — Fall 2026",
      "Lecture 1 · Deck 3 — App Router only",
      "React components + Next.js file-system routing. No Vite SPA setup",
    ],
  },
  {
    id: "react-is",
    title: "React = data → UI",
    kind: "content",
    bullets: [
      "A **component** is a function that turns **data** (props, state) into **UI** (JSX)",
      "You describe what the screen should look like. React updates the DOM to match",
      "Compose small components into pages. Pages are just components that own a URL",
      "This course writes components as TypeScript functions in `.tsx` files",
    ],
  },
  {
    id: "user-component",
    title: "Example: a User component",
    kind: "demo",
    bullets: [
      "`function User({ name, email }: { name: string; email: string }) {`",
      "`  return (`",
      "`    <div>`",
      "`      <h2>{name}</h2>`",
      "`      <p>{email}</p>`",
      "`    </div>`",
      "`  );`",
      "`}`",
      "Same function, different props → different UI. That is the whole idea",
    ],
    interactiveHint:
      "Change `name` and watch only the heading text change. The component did not care where the data came from.",
  },
  {
    id: "create-next-app",
    title: "Scaffold with create-next-app",
    kind: "demo",
    bullets: [
      "From `~/2026/fall/webdev` (sibling to the Node demo, not inside it):",
      "`npx create-next-app@latest kambaz-next-js`",
      "The first run may ask to install the `create-next-app` package — accept",
      "Course spelling: **kambaz-next-js** — same kambaz name as the LMS prototype",
      "This is the client you will later push to GitHub and deploy on Vercel",
    ],
  },
  {
    id: "defaults",
    title: "Accept the App Router defaults",
    kind: "content",
    bullets: [
      "**TypeScript** — Yes",
      "**ESLint** — Yes",
      "**Tailwind CSS** — Yes",
      "**`src/` directory** — Yes (default). The book’s screenshots also work if you chose No and use top-level `app/`",
      "**App Router** — Yes (required for this course)",
      "**Turbopack** for `next dev` — Yes",
      "**`@/*` import alias** — keep the default (do not customize)",
    ],
    interactiveHint:
      "If a prompt offers Pages Router, say no. This course is App Router only.",
  },
  {
    id: "npm-run-dev",
    title: "npm run dev",
    kind: "demo",
    bullets: [
      "`cd kambaz-next-js`",
      "`npm run dev`",
      "Next.js prints a local URL — usually `http://localhost:3000`",
      "Open it in **Google Chrome**. You should see the starter page",
      "Stop anytime with Ctrl+C; start again with `npm run dev`",
    ],
  },
  {
    id: "ide",
    title: "Open the folder in the IDE",
    kind: "content",
    bullets: [
      "File → Open Folder → `kambaz-next-js` (VS Code or Cursor)",
      "Use **Terminal → New Terminal** inside the IDE so commands run in the project root",
      "Explorer should show `app/` (or `src/app/`), `public/`, `package.json`",
      "This course assumes Chrome + VS Code or Cursor",
    ],
  },
  {
    id: "structure",
    title: "What just got created",
    kind: "content",
    bullets: [
      "`node_modules/` — installed packages. Never commit this",
      "`public/` — static files (images) served as `/filename`",
      "`app/` — **routes**. A folder + `page.tsx` becomes a URL",
      "`app/layout.tsx` — the root shell (`<html>`, `<body>`, fonts, CSS import)",
      "`app/page.tsx` — the home route `/`",
      "`package.json` — scripts (`dev`, `build`, `start`) and dependencies",
    ],
  },
  {
    id: "app-router-only",
    title: "App Router only — no Vite SPA leftover",
    kind: "content",
    bullets: [
      "Older lecture notes used **Vite** + `createRoot` + `main.tsx` + an `App.tsx` counter",
      "We **do not** do that here. There is no `index.html` mount point you own",
      "Next.js is the bundler, the server, and the router",
      "You add routes by adding folders under `app/`, not by calling `createRoot`",
      "If a tutorial starts with Vite + React, close it — it will fight this course",
    ],
  },
  {
    id: "comment-globals",
    title: "Comment out globals.css in the layout",
    kind: "demo",
    bullets: [
      "The starter imports Tailwind via `app/globals.css` (or `src/app/globals.css`)",
      "For Chapter 1 HTML exercises we want the browser’s default look",
      "In `app/layout.tsx`, comment out the CSS import. Leave the rest of the file alone",
      "`// import \"./globals.css\";`",
      "Refresh `/`. The starter page looks unstyled. That is expected",
    ],
    interactiveHint:
      "Do not delete `globals.css`. You will turn Tailwind back on in Chapter 2.",
  },
  {
    id: "welcome-page",
    title: "Replace the home page",
    kind: "demo",
    bullets: [
      "Open `app/page.tsx` and replace the starter markup with a simple heading:",
      "`export default function Home() {`",
      "`  return <h1>Welcome to Web Dev</h1>;`",
      "`}`",
      "Save. With `npm run dev` running, `/` should show that h1",
    ],
  },
  {
    id: "lab1-route",
    title: "Add a Lab 1 route",
    kind: "demo",
    bullets: [
      "Create `app/labs/lab1/page.tsx` (make the folders if needed):",
      "`export default function Lab1() {`",
      "`  return (`",
      "`    <div id=\"wd-lab1\">`",
      "`      <h2>Lab 1</h2>`",
      "`    </div>`",
      "`  );`",
      "`}`",
      "File path **is** the URL: `app/labs/lab1/page.tsx` → `/labs/lab1`",
    ],
  },
  {
    id: "why-page-tsx",
    title: "Why the file is named page.tsx",
    kind: "content",
    bullets: [
      "`page.tsx` is reserved. Next.js exposes that folder as a public route",
      "`app/page.tsx` → `/`",
      "`app/labs/page.tsx` → `/labs` (you can add this later as a table of contents)",
      "`app/labs/lab1/page.tsx` → `/labs/lab1`",
      "Other `.tsx` files are components you **import**. Only `page.tsx` creates a URL",
    ],
  },
  {
    id: "link-to-lab1",
    title: "Link home to Lab 1",
    kind: "demo",
    bullets: [
      "In Next.js, in-app navigation uses `Link` from `next/link` — not a raw `<a>` for internal routes",
      "On `app/page.tsx`:",
      "`import Link from \"next/link\";`",
      "`<h1>Welcome to Web Dev</h1>`",
      "`<Link href=\"/labs/lab1\">Lab 1</Link>`",
      "Click it. The App Router navigates to `/labs/lab1` without a full classic page reload",
    ],
    interactiveHint:
      "Use `Link` for routes inside this app. Use `<a>` for GitHub, Canvas, and other sites.",
  },
  {
    id: "compose",
    title: "Components compose",
    kind: "content",
    bullets: [
      "Keep `page.tsx` thin. Import smaller components for each exercise",
      "`HeadingTags.tsx` is a component, not a route — no `page.tsx` in that file’s folder",
      "Lab 1 stays one URL (`/labs/lab1`) while the file list grows",
      "Composition: `<Lab1>` renders `<HeadingTags />`, `<AnchorTag />`, …",
      "Same idea as `<User />`: pages assemble components; components assemble HTML",
    ],
  },
  {
    id: "user-on-page",
    title: "Drop User onto a page",
    kind: "demo",
    bullets: [
      "Create `app/components/User.tsx` with the User function from earlier",
      "In `app/page.tsx` render `<User name=\"Ada\" email=\"ada@example.com\" />`",
      "You did not register a route. You imported a component",
      "That is App Router composition — not an `App.tsx` tree mounted by hand",
    ],
  },
  {
    id: "devtools",
    title: "DevTools: see what React rendered",
    kind: "demo",
    bullets: [
      "Chrome → More Tools → Developer Tools (or F12 / ⌥⌘I)",
      "Elements panel: the **DOM** — the in-memory tree the browser paints",
      "Find your `<h1>Welcome to Web Dev</h1>` and the Lab 1 `div#wd-lab1`",
      "The HTML source and the live DOM can differ after React hydrates. Elements shows the live tree",
    ],
    interactiveHint:
      "Right-click the heading → Inspect. Confirm the node matches the JSX you wrote.",
  },
  {
    id: "dom-parse",
    title: "How the browser parses the page",
    kind: "content",
    bullets: [
      "Next.js sends HTML for the route. The browser **parses** it into the DOM",
      "CSS (when we turn it back on) attaches styles to those nodes",
      "JavaScript/React can add, replace, or update nodes after the first parse",
      "Inspecting the DOM is how you debug “I saved the file but the page looks wrong”",
      "If the file is saved and `npm run dev` is running, a refresh should show the new markup",
    ],
  },
  {
    id: "routing-rules",
    title: "Routing rules to remember",
    kind: "content",
    bullets: [
      "Folders under `app/` are path segments",
      "A route exists only when that folder contains `page.tsx`",
      "`layout.tsx` wraps child routes (root layout wraps everything)",
      "Dynamic segments like `[slug]` come later — we will use one for these lecture decks",
      "There is no `main.tsx` entry you edit. Next.js owns the bootstrap",
    ],
  },
  {
    id: "not-vite-counter",
    title: "What we are not building",
    kind: "content",
    bullets: [
      "Not a Vite project",
      "Not `ReactDOM.createRoot(document.getElementById(\"root\")).render(<App />)`",
      "Not a standalone `App.tsx` with `useState` click-counter as the “hello world”",
      "Hello world here is: a `page.tsx`, a second route, and a `Link` between them",
      "State and events arrive in Chapter 4. HTML structure is Chapter 1",
    ],
  },
  {
    id: "src-vs-app",
    title: "src/app vs app/",
    kind: "content",
    bullets: [
      "If you accepted `src/`, your files live in `src/app/page.tsx` and `src/app/labs/lab1/page.tsx`",
      "URLs do **not** include `src` — it is only a disk folder",
      "The course book often shows `app/` at the repo root (No to `src/`). Both are App Router",
      "Pick one layout and stay consistent so import paths and screenshots match your disk",
    ],
  },
  {
    id: "kambaz-name",
    title: "Naming: kambaz",
    kind: "content",
    bullets: [
      "The LMS prototype is **Kambaz** — that is the spelling in the book and repos",
      "Project folder: `kambaz-next-js` (or `webdev-client` if you follow the book’s repo name)",
      "Use that spelling in the folder name so it matches the book and Kambaz screens",
    ],
  },
  {
    id: "layout-wraps",
    title: "layout.tsx wraps every route",
    kind: "content",
    bullets: [
      "`app/layout.tsx` is the root shell: `<html>`, `<body>`, fonts, and the CSS import",
      "Every `page.tsx` renders as `{children}` inside that layout",
      "You do not mount the tree yourself — Next.js calls the layout, then the page",
      "Commenting out `globals.css` in the layout is how we turn off starter styles for Lab 1",
      "Nested `layout.tsx` files (later) wrap only that folder’s routes",
    ],
  },
  {
    id: "check",
    title: "Check before you sit down",
    kind: "content",
    bullets: [
      "`npm run dev` serves `/` with **Welcome to Web Dev**",
      "`/labs/lab1` renders the Lab 1 heading",
      "Home has a `Link` to Lab 1",
      "`globals.css` is commented out in the root layout",
      "You did not add a Vite config or a `createRoot` main file",
    ],
  },
  {
    id: "next-up",
    title: "Next: commit to GitHub",
    kind: "title",
    bullets: [
      "The app runs only on your machine until Git sees it",
      "Deck 4: `.gitignore`, a GitHub repo, `git push -u origin main`",
    ],
  },
];
