import type { LectureSlide } from "../types";

export const INTRO_TO_WEB_DEVELOPMENT_SLIDES: LectureSlide[] = [
  {
    id: "title",
    title: "WEB DEV",
    kind: "title",
    bullets: [
      "Introduction to Web Development",
      "Jose Annunziato",
    ],
  },
  {
    id: "internet",
    title: "What is the Internet?",
    kind: "content",
    bullets: [
      "A global **network of computers**. **Network of networks**",
      "Researched by **DARPA** early 60s to survive WWIII",
      "**ARPANET**, a precursor, connected military and academic networks in 1980s",
      "Commercial use expanded in 1990s to what we have today",
    ],
  },
  {
    id: "web",
    title: "What is the Web?",
    kind: "content",
    bullets: [
      "AKA The **World Wide Web** or **WWW** or just The Web",
      "Technologies that use the Internet to share formatted documents connected to one another",
      "Invented by **Tim Berners-Lee** in '89, a physicist at **CERN**",
      "Documents are formatted in **HTML** (Hypertext Markup Language)",
    ],
  },
  {
    id: "browsers-urls",
    title: "What is the Web?",
    kind: "content",
    bullets: [
      "**Browsers** fetch HTML documents from servers connected by the internet",
      "Documents are found with **URLs** (Uniform Resource Locator)",
      "HTML documents format (hyper) text as **anchors** that refer or link to other documents",
    ],
  },
  {
    id: "network-of-networks",
    title: "A network of networks",
    kind: "content",
    bullets: [
      "**THE INTERNET** — independently operated **networks** that peer with one another",
      "Each network has **clients** and **servers**",
      "No single owner. Packets hop from network to network",
    ],
    diagram: "network-of-networks",
  },
  {
    id: "client-server",
    title: "The Client Server Architecture",
    kind: "content",
    bullets: [
      "**CLIENTS** — browsers, desktop apps, games. **HTML**, **CSS**, **JavaScript**, **React**",
      "**SERVERS** — Node, Express, mail, FTP. **PHP**, Java, Python, **JavaScript**",
      "**RESOURCES** — databases (**Mongo**), documents, files",
      "They talk **HTTP REQUEST** and **HTTP RESPONSE** over the Internet",
    ],
    diagram: "client-server",
  },
  {
    id: "milestones",
    title: "Some Milestones",
    kind: "content",
    bullets: [
      "**1960s** — The Internet",
      "**1970s** — Client-server architecture",
      "**1980s** — Personal computers",
      "**1990s** — The World Wide Web",
      "**2000s** — Web Applications",
      "**2010s** — Mobile computing, big data",
      "**2020s** — Neuralink / Starlink / TeslaBot / Claude?",
    ],
  },
  {
    id: "server-frameworks",
    title: "Server Frameworks",
    kind: "content",
    bullets: [
      "**1993** — Common Gateway Interface (Perl, C++, …)",
      "**1995** — **PHP**",
      "**1999** — Java 2 Enterprise Edition (J2EE)",
      "**2000** — **.NET** (ASPs, Visual Basic, C#, …)",
      "**2005** — Ruby on Rails · **Django** (Python)",
      "**2009** — **Node.js** (JavaScript)",
      "**2010** — Flask (Python)",
    ],
  },
  {
    id: "ssr",
    title: "Server Side UI Rendering",
    kind: "content",
    bullets: [
      "Server **executes** HTML with embedded source code",
      "Sends a **finished page** to the client",
      "Classic PHP / JSP / Rails — and Next.js **Server Components**",
    ],
    diagram: "ssr",
  },
  {
    id: "client-frameworks",
    title: "Client Frameworks",
    kind: "content",
    bullets: [
      "**1995** — **JavaScript** (Netscape)",
      "**1996** — Adobe Flash",
      "**2006** — jQuery",
      "**2010** — Knockout · AngularJS · Backbone",
      "**2013** — **React** (Facebook)",
      "**2014** — Vue · **2016** — Angular 2+ · **Svelte** · **Next.js** (server first)",
      "**2021–22** — SolidJS, Remix, Astro, Qwik",
    ],
  },
  {
    id: "csr",
    title: "Client Side UI Rendering",
    kind: "content",
    bullets: [
      "Server sends a shell; **JavaScript in the browser** builds the UI",
      "Clicks and fetches update the page without a full reload",
      "**React** started here. **Next.js** can hydrate a server-rendered page, then behave like CSR",
    ],
    diagram: "csr",
  },
  {
    id: "web-app-se",
    title: "Web Application Development",
    kind: "content",
    bullets: [
      "Applying **software engineering** to build applications using the Web as a framework",
      "**Requirements**",
      "**Data modeling**",
      "**Interprocess communication**",
      "**Data storage/retrieval**",
      "**User interface design**",
    ],
  },
  {
    id: "teams",
    title: "Working in Teams",
    kind: "content",
    bullets: [
      "The code belongs to the **team**",
      "**Best practices** — source control, pull requests, code review",
      "**Naming conventions**, understandability",
      "**Application structure**",
      "Planification, communication",
    ],
  },
  {
    id: "large-projects",
    title: "Working in Large Projects",
    kind: "content",
    bullets: [
      "**Scalability**",
      "**Maintainability**",
      "Software development methodologies — requirements, design, implementation, feedback, testing",
      "**Incremental** software development",
    ],
  },
  {
    id: "architecture",
    title: "Architecture",
    kind: "content",
    bullets: [
      "**Client-server** architecture",
      "**Multitier** architecture",
      "**Separation of concern** (SoC)",
      "**Model View Controller** (MVC)",
      "Object-oriented programming",
      "Aspect-oriented programming",
    ],
  },
  {
    id: "patterns",
    title: "Design Patterns",
    kind: "content",
    bullets: [
      "**Singleton**",
      "**Factory**",
      "**Service**",
      "**Model View Controller** (MVC)",
      "**Data access object** (DAO)",
      "**Inversion of control** (IOC)",
    ],
  },
];
