/**
 * Export Canvas Classic Quiz QTI for Fall 2026 fallback quizzes.
 *
 * Usage:
 *   npx tsx scripts/export-canvas-fallback-qti.ts
 *   npx tsx scripts/export-canvas-fallback-qti.ts --out scripts/canvas-fallback/out
 *
 * Writes Canvas non_cc_assessments-shaped QTI, assessment_meta.xml,
 * a QTI-zip tree (imsmanifest + quizzes), and a small sample fragment.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  CANVAS_FALLBACK_QUIZZES,
  canvasFallbackIdent,
  canvasQuizDescriptionHtml,
} from "../lib/quiz-exam/canvas-copy";
import { buildCanvasFallbackBanks } from "../lib/quiz-exam/canvas-fallback-banks";
import {
  renderCanvasAssessmentMeta,
  renderCanvasQtiAssessment,
  renderQtiGroup,
  renderQtiPackageManifest,
  pointsPerItem,
} from "../lib/question-bank/qti";

const DEFAULT_OUT = "scripts/canvas-fallback/out";

function parseOutDir(argv: string[]): string {
  const flag = argv.indexOf("--out");
  if (flag !== -1 && argv[flag + 1]) {
    return resolve(process.cwd(), argv[flag + 1]);
  }
  return resolve(process.cwd(), DEFAULT_OUT);
}

function write(path: string, contents: string): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, contents, "utf8");
}

function main(): void {
  const outDir = parseOutDir(process.argv.slice(2));
  const banks = buildCanvasFallbackBanks();
  const qtiDir = join(outDir, "qti");
  const metaDir = join(outDir, "assessment_meta");
  const zipDir = join(outDir, "qti-zip");
  const sampleDir = resolve(process.cwd(), "scripts/canvas-fallback/sample");

  const manifestEntries: Array<{ ident: string; href: string; title: string }> = [];

  for (const quiz of CANVAS_FALLBACK_QUIZZES) {
    const bank = banks[quiz.quizId];
    if (!bank || bank.groups.length === 0) {
      throw new Error(`No Canvas fallback questions for ${quiz.quizId}`);
    }
    const ident = canvasFallbackIdent(quiz.quizId);
    const qti = renderCanvasQtiAssessment(bank, ident, quiz.canvasTitle);
    const meta = renderCanvasAssessmentMeta({
      ident,
      title: quiz.canvasTitle,
      descriptionHtml: canvasQuizDescriptionHtml(quiz),
      unlockAt: quiz.unlockAt,
      dueAt: quiz.dueAt,
      lockAt: quiz.lockAt,
      pointsPossible: 100,
      allowedAttempts: 1,
    });
    const fileName = `${quiz.quizId}.xml.qti`;
    write(join(qtiDir, fileName), qti);
    write(join(outDir, "non_cc_assessments", `${ident}.xml.qti`), qti);
    write(join(metaDir, `${quiz.quizId}.assessment_meta.xml`), meta);
    write(join(outDir, ident, "assessment_qti.xml"), qti);
    write(join(outDir, ident, "assessment_meta.xml"), meta);
    write(join(zipDir, `${quiz.quizId}.xml`), qti);
    manifestEntries.push({
      ident,
      href: `${quiz.quizId}.xml`,
      title: quiz.canvasTitle,
    });
  }

  write(join(zipDir, "imsmanifest.xml"), renderQtiPackageManifest(manifestEntries));

  const q1 = banks.q1;
  const firstGroup = q1.groups[0];
  if (!firstGroup) {
    throw new Error("Q1 bank has no groups");
  }
  const samplePoints = pointsPerItem(q1.groups.length);
  const sample = [
    `<!-- Sample Canvas non_cc_assessments fragment: Q1 group "${firstGroup.name}".`,
    `     Regenerated by: npm run canvas:export-qti`,
    `     Full quizzes live under scripts/canvas-fallback/out/. -->`,
    renderQtiGroup(firstGroup, samplePoints),
    "",
  ].join("\n");
  write(join(sampleDir, "q1-acronyms-group.fragment.xml"), sample);

  const index = {
    generatedAt: new Date().toISOString(),
    rebuild: "npm run canvas:export-qti",
    quizzes: CANVAS_FALLBACK_QUIZZES.map((quiz) => ({
      quizId: quiz.quizId,
      title: quiz.canvasTitle,
      ident: canvasFallbackIdent(quiz.quizId),
      groups: banks[quiz.quizId].groups.length,
      questions: banks[quiz.quizId].groups.reduce(
        (sum, group) => sum + group.questions.length,
        0,
      ),
      qti: `qti/${quiz.quizId}.xml.qti`,
      meta: `assessment_meta/${quiz.quizId}.assessment_meta.xml`,
    })),
  };
  write(join(outDir, "index.json"), `${JSON.stringify(index, null, 2)}\n`);

  const root = dirname(fileURLToPath(import.meta.url));
  console.log(`Wrote Canvas fallback QTI under ${outDir}`);
  console.log(`Sample fragment: ${join(root, "canvas-fallback/sample/q1-acronyms-group.fragment.xml")}`);
  console.log("Zip for Canvas QTI import: zip the files in qti-zip/ (imsmanifest.xml + *.xml).");
}

main();
