import type { ProjectDoc } from "../types";

export const open_endedDoc = {
  slug: "open-ended",
  title: "Open-Ended Web Application",
  subtitle: "Final Project Requirements",
  description: "Design and build an original full-stack application with search, details, profiles, roles, and a third-party API.",
  blocks: [
    { type: "h", level: 1, text: "Page Requirements" },
    { type: "p", text: "Your Web application must have at least the following six (6) distinct screens: Login/Register, Home, Profile, Search/results, Details. Below is a proposed navigation diagram" },
    { type: "img", src: "/project/open-ended/01.png", alt: "Navigation diagram for Home, Search, Details, Profile, Login, and Register screens.", width: 2022, height: 1013 },
    { type: "p", text: "You are free to implement an alternative navigation as long as provide equivalent functionality" },
    { type: "h", level: 2, text: "Home page requirements" },
    { type: "p", text: "Home - this is the landing page of your web application. It is the first page users should see when they visit your website. The home page must fulfill the following requirements." },
    { type: "li", depth: 0, text: "Must be mapped to either the root context (\"/\") or (\"/home\")." },
    { type: "li", depth: 0, text: "Must be the first page when visiting the website" },
    { type: "li", depth: 0, text: "Must display generic content for anonymous users. The content must be dynamic based on the latest data. For instance, you might display snippets and links to the most recent post, review, or member who recently joined" },
    { type: "li", depth: 0, text: "Must display specific content for the logged in user. The content must be dynamic based on the most recent data entered by the logged in user. For instance, you might display snippets and links to the most recent post or review created by the logged in user" },
    { type: "li", depth: 0, text: "Must be clear to what the Web site is about and must look polished and finished" },
    { type: "h", level: 2, text: "Profile page requirements" },
    { type: "p", text: "The profile page where users can see all the information about themselves and other users. It could have several sections for personal information, other people they are following, who is following them, and links to related content associate with the user. It could hide some personal information depending on who is logged in and how a user configured their profile" },
    { type: "li", depth: 0, text: "Must allow users to change their personal information. If a user is logged in then they can see their profile including sensitive information such as email and phone" },
    { type: "li", depth: 0, text: "Must be accessible to other users including anonymous users" },
    { type: "li", depth: 0, text: "Must hide personal/private information from others visiting the profile. If a user is visiting someone else's profile, then they can't see that other user's sensitive information" },
    { type: "li", depth: 0, text: "Must be mapped to \"/profile\" for displaying the profile of the currently logged in user" },
    { type: "li", depth: 0, text: "Must be mapped to \"/profile/{profileId}\" for displaying someone else's profile" },
    { type: "li", depth: 0, text: "Must group similar/related data into distinguishable groups, e.g., Following, Followers, Review, Favorites, etc." },
    { type: "li", depth: 0, text: "Must display lists of snippets and links of all data related to a user. For instance, display a list of links to all the favorite movies, list of links of users they are following, etc. For instance:" },
    { type: "li", depth: 1, text: "If user is following other users, then those users must be listed in the profile and a link must navigate to that other users profile" },
    { type: "li", depth: 1, text: "If the user has bookmarked something, then it should be listed in the profile and a link must navigate to that something" },
    { type: "li", depth: 1, text: "If the user has commented, or reviewed, or created some content, then there must be a functionality to list a summary of that content and navigate to that content" },
    { type: "li", depth: 1, text: "You decide how to present, display, format the information" },
    { type: "li", depth: 0, text: "The profile page may be implemented as several pages" },
    { type: "h", level: 2, text: "Search/Search Results page requirements" },
    { type: "p", text: "The website should provide users the capability to search content from a remote service and display a summary of the results. Search and results can be in the same page or in separate pages. Maybe the search bar can be in the home page, and the results in a separate page. Or both in a separate search page. The results could be formatted in a list, or a grid, or a table. They can have a short description, and a thumbnail of the result. For instance, if you chose movies as your domain objects, then users must be able to search for movies. Users must be able to see a summary of the search results and navigate to a detail page that shows a detail view of the result. The search and results page must fulfill the following requirements." },
    { type: "li", depth: 0, text: "Must provide a form to search a remote API, not your own API" },
    { type: "li", depth: 0, text: "Must provide a summarized list of results matching the search criteria. Results must come from the remote API, not your local database" },
    { type: "li", depth: 0, text: "Must provide a link/button to navigate to the details page (see below)" },
    { type: "li", depth: 0, text: "Must be mapped to /search when no search has been executed and no results exist" },
    { type: "li", depth: 0, text: "Must be mapped to /search/{search criteria} or /search?criteria={search criteria} when a search has been executed and according results shown" },
    { type: "li", depth: 0, text: "Can augment the results with related data in your local databases" },
    { type: "li", depth: 0, text: "The search and results page can be implemented as either a single page or separate pages. In that case a separate route can be used such as /results/{search criteria} or /results?criteria={search criteria}" },
    { type: "h", level: 2, text: "Details page requirements" },
    { type: "p", text: "The details page allow users to view a details view of the search result. They can see more information when they click on the search result. The details page must fulfill the following requirements." },
    { type: "li", depth: 0, text: "Must retrieve details from the remote API based on some unique identifier provided as a parameter from the search/results page" },
    { type: "li", depth: 0, text: "Must display additional related data from the local database. For instance, if you are displaying the details of a movie, some other folks might have reviewed the movie. All reviews related to the movie must be shown in all or partial form" },
    { type: "li", depth: 0, text: "Must provide links to related data/users. For instance, if you are displaying the details of a movie, and below you are displaying a list of reviews for that movie, provide links to the profile pages of folks who wrote the reviews for the movie" },
    { type: "li", depth: 0, text: "Must be mapped to /details/{unique identifier} or /details?identifier={unique identifier} where unique identifier uniquely identies the item being displayed" },
    { type: "h", level: 2, text: "Login/Register page requirements" },
    { type: "p", text: "The login and register page allow users to register with the web site and then login later on" },
    { type: "li", depth: 0, text: "Must allow users to register and create a new account" },
    { type: "li", depth: 0, text: "Must allow choosing a role(s) for a user. For instance, when signing up you can provide a checkbox or radio button to select the role or roles. Alternatively provide an admin role and admin page that allows configuring user role(s)" },
    { type: "li", depth: 0, text: "Must allow login in and identifying themselves" },
    { type: "li", depth: 0, text: "Must disallow access to at least one Web page unless logged in" },
    { type: "li", depth: 0, text: "Must allow access to all other Web pages even when not logged in" },
    { type: "li", depth: 0, text: "Must adapt content based on whether user is logged in or not for at least the Home page and Profile page" },
    { type: "li", depth: 0, text: "Must force login only when identity is required. For instance, an anonymous user might search for movies and visit the details page for a particular movie without needing to login. But if they attempt to like the movie, or rate it, or comment on it, or write a review, or follow someone, the application must request the user to login. Most of the Web application must be available without login (see me if not)" },
    { type: "li", depth: 0, text: "Must be mapped to /login if both login and register are implemented in the same page" },
    { type: "li", depth: 0, text: "The login and register page can be implemented as a single page or as two separate pages. In that case the login page must be mapped to /login and the register page must be mapped to /register" },
    { type: "h", level: 1, text: "Styling Requirements" },
    { type: "h", level: 2, text: "Responsive design requirements" },
    { type: "p", text: "Web application must be usable in a desktop, tablet or phone" },
    { type: "li", depth: 0, text: "Web pages must be responsive at any width of the browser" },
    { type: "li", depth: 0, text: "Elements must never overlap each other unintentionally" },
    { type: "li", depth: 0, text: "Elements must not wrap unintentionally" },
    { type: "li", depth: 0, text: "Scrollbars must not appear unintentionally" },
    { type: "li", depth: 0, text: "Embedded scrollbars must be avoided unless specifically necessary" },
    { type: "li", depth: 0, text: "Must use scrollbars only when it is absolutely necessary" },
    { type: "p", text: "You are free to layout the Web pages anyway you wish, but the following behaviors must be demonstrated somewhere in your pages. At least one of the following:" },
    { type: "h", level: 2, text: "CSS libraries" },
    { type: "p", text: "Use libraries such as bootstrap CSS, JavaScript, and HTML templates. Feel free to override the look and feel to achieve a unique style." },
    { type: "h", level: 2, text: "White spacing" },
    { type: "p", text: "Use white spacing to properly format space around and between content" },
    { type: "li", depth: 0, text: "Padding - must use padding to avoid content being flush with their parent containers" },
    { type: "li", depth: 0, text: "Margin - must use margin to add space between content" },
    { type: "li", depth: 0, text: "Justification - must use justification to format left, center, right, or justified content" },
    { type: "li", depth: 1, text: "Text content must be left justified" },
    { type: "li", depth: 1, text: "Numeric content must be right justified" },
    { type: "li", depth: 1, text: "Currency must be properly formatted with symbols and decimals" },
    { type: "li", depth: 1, text: "Dates must be properly and consistently formatted" },
    { type: "li", depth: 0, text: "Wrapping - must avoid unnecessary/unintentional wrapping. Especially make sure content wraps properly as you resize the browser" },
    { type: "h", level: 2, text: "Navigation requirements" },
    { type: "p", text: "Navigation between pages must be clear. Where applicable, it should evident how to backtrack from a page back to its parent page. It should be clear how to navigate to other places of the Web application." },
    { type: "h", level: 2, text: "Contrast requirements" },
    { type: "p", text: "The Web application must use a palette of colors and transparencies that uses contrast between foreground and background to facilitate reading" },
    { type: "h", level: 2, text: "Labels requirements" },
    { type: "p", text: "All content must be properly labeled. All form elements must have placeholders" },
    { type: "h", level: 2, text: "Look and feel requirements" },
    { type: "p", text: "The Web application must look professional and have a polished, finished look. You should be proud to showcase your Web application and brag about to a potential employer" },
    { type: "h", level: 2, text: "Consistency requirements" },
    { type: "p", text: "All content must be consistent across the application. Use a consistent set of colors, fonts, sizes, paddings, margins, justification, formatting, wrapping, look and feel, white spaces, etc." },
    { type: "h", level: 2, text: "User experience requirements" },
    { type: "p", text: "The Web application must meet the following user experience best practices" },
    { type: "li", depth: 0, text: "Navigating between master/slave pages must be clearly marked" },
    { type: "li", depth: 0, text: "Currently logged in user must be clearly marked" },
    { type: "li", depth: 0, text: "Touch or click areas must be as large as possible. For instance, don't force the user to click on small target areas such as a link if there is also the possibility of clicking on a related large icon or image. Clicking on the label of a radio or checkbox button should also toggle the button. Clicking on the label of a text input should cause focus on the input" },
    { type: "li", depth: 0, text: "Errors must be clearly marked and options to fix them must be provided" },
    { type: "li", depth: 0, text: "Navigating to the home page must be clearly marked" },
    { type: "li", depth: 0, text: "Navigating to the profile must be clearly marked" },
    { type: "li", depth: 0, text: "The URL must have a meaningful name" },
    { type: "li", depth: 0, text: "Your website\u2019s privacy policy must be made available to users upon their first visit to the site, and easily accessible for subsequent review" },
    { type: "h", level: 1, text: "Architectural requirements" },
    { type: "li", depth: 0, text: "Global variables and functions - Use modules/classes/IIFEs to namespace your variables and functions to avoid littering the namespace" },
    { type: "li", depth: 0, text: "Dynamic content loading - load HTML content dynamically using client side routing, views, and templates to avoid reloading the entire page" },
    { type: "li", depth: 0, text: "Controllers/Components/Event handlers - implement controllers or components to handle user interaction/events, provide data to the view/template" },
    { type: "li", depth: 0, text: "State - avoid maintaining state in temporary client variables. State must be encoded as part of the URL. If a Web page is reloaded the content should look the same, unless it is time sensitive. For instance, if you search for a movie with a term such as \"batman\" and are now showing the search results for \"batman\" movies, then reloading the page should again show the same search result" },
    { type: "li", depth: 0, text: "Web service client - centralize Web service and data access in services that can be shared across the application" },
    { type: "li", depth: 0, text: "File structure - organize your files into a consistent file structure as shown in class and assignments" },
    { type: "h", level: 1, text: "User requirements" },
    { type: "p", text: "The Web application must provide user management functionality that allow users to register, login, logout, and visit their profile. The navigation must adapt depending on whether a user is logged in or not, and depending on their role in the application. There must be at least two types of users or roles (3 for graduate students). For instance, a user can be a buyer or a seller, a user can be a book author or just a passive reader. A user can be a regular user or an admin. The user interface must adapt to the user role by hiding certain links, or entire pages and functionality. For instance, admin users might have access to admin pages that would otherwise be inaccessible to the rest of the users of the application. The use cases for the two types of users must be different enough to warrant different user interfaces. It is ok for users to have some use cases in common such as login, register, and some profile content. But most of the use cases must need distinct user interfaces to fulfill the specific use cases for the specific type of user." },
    { type: "h", level: 2, text: "User Roles" },
    { type: "p", text: "Identify at least 2 types of human users that would use your application (3 for graduate). Example users might be" },
    { type: "li", depth: 0, text: "Online store application: sellers, buyers" },
    { type: "li", depth: 0, text: "Online project management: developers, quality assurance, project managers, business analysts" },
    { type: "li", depth: 0, text: "Online restaurant: cooks, waiters, delivery, receptionists, manager, owner" },
    { type: "li", depth: 0, text: "Online sports: player, coach, director, spectator, fan" },
    { type: "li", depth: 0, text: "Online fishing journal: fisherman, partner, boat captain" },
    { type: "li", depth: 0, text: "Online university: students, faculty, staff" },
    { type: "p", text: "The navigation and user interface must adapt depending on whether a user is logged in or not, and depending on the role of user. Your application must support at least two user roles. For instance, a user can be buyer and a seller, a user can be a book author or just a passive reader. The user interface must adapt to the user role by hiding certain links, or entire pages and functionality. For instance, admin users might have access to admin pages that would otherwise be inaccessible to the rest of the users of the application. A particular user can have multiple roles, but they can only be in a particular role at any one time, or, if you prefer, the application can provide a mechanism to toggle between roles, but the interface must be significantly different for different user roles." },
    { type: "h", level: 3, text: "Anonymous User Requirements" },
    { type: "p", text: "Your project must support some functionality for anonymous users and only force users to login if user identity is required to fulfill a service. For instance, in an online store, anonymous users should be able to search for products, view product details, read product reviews, etc. If a user would like to bookmark a product, or comment on a product, or add a product to a shopping cart, then, and only then, would the Website ask the user to identify themselves or register." },
    { type: "h", level: 3, text: "End User Roles Requirements" },
    { type: "p", text: "Your application must support at least two end user roles. Here are a couple of examples of how the interface might be different for different roles. The interfaces are based on the goals each actor wants to accomplish" },
    { type: "li", depth: 0, text: "Online store application - depending on their roles, users will have different user interfaces" },
    { type: "li", depth: 1, text: "sellers can - CRUD products, stores, orders, e.g., buyers can create a store and add products to the store, then change their descriptions, change their prices, view online orders, fulfill the orders, cancel the orders, etc." },
    { type: "li", depth: 1, text: "buyers can - search for products, add to a shopping list, checkout, view their orders, cancel an order, review products" },
    { type: "li", depth: 0, text: "Online university application - depending on their roles, users will have different user interfaces" },
    { type: "li", depth: 1, text: "faculty can - CRUD courses, sections, assignments, quizzes" },
    { type: "li", depth: 1, text: "students can - search courses/sections, register for sections, take quizzes, submit assignments" },
    { type: "h", level: 1, text: "Web Service Requirements" },
    { type: "p", text: "Use Node.js Express or Java to create RESTful Web services as follows" },
    { type: "li", depth: 0, text: "URLs must capture the relationship between the entities of your application" },
    { type: "li", depth: 0, text: "Use path parameters and query parameters appropriately as discussed in class" },
    { type: "li", depth: 0, text: "Use various HTTP methods and verbs when creating, deleting, reading, and updating data" },
    { type: "li", depth: 0, text: "Web services should use a model to interact with the data" },
    { type: "li", depth: 0, text: "Implement Web services in separate files as needed" },
    { type: "li", depth: 0, text: "Use promises where necessary" },
    { type: "h", level: 1, text: "Database Requirements" },
    { type: "p", text: "Use Mongoose to create a data model that interacts with a MongoDB database or JPA to create a Java data model that maps to a MySQL relational database. You are free to use any database." },
    { type: "h", level: 2, text: "Data model requirements" },
    { type: "p", text: "Create a Mongoose data models or Java entities and repositories that provides an API to interact with the database. Use promises where necessary. The API should provide standard CRUD operations plus additional high level operations you might need. Here are some operations you should consider" },
    { type: "li", depth: 0, text: "Create - inserts a document in the database" },
    { type: "li", depth: 0, text: "Read One - reads a document from the database, typically by id" },
    { type: "li", depth: 0, text: "Read All - reads all the documents from the database for a given type" },
    { type: "li", depth: 0, text: "Read Predicate - reads all documents that match a predicate" },
    { type: "li", depth: 0, text: "Update - updates a document, typically the one matching an id" },
    { type: "li", depth: 0, text: "Delete - deletes a document, typically by id" },
    { type: "h", level: 2, text: "Data model complexity requirements" },
    { type: "p", text: "The following are requirements about the number of tables, classes, and relationships between the various data entities" },
    { type: "li", depth: 0, text: "At least two domain object models - create a schema to capture information about your particular domain. For instance, if your domain is movies, then the schema might have properties such as title, rating, date, directors, actors, etc (3 domains for graduate students)" },
    { type: "li", depth: 0, text: "At least two user models - each user type or role should have its own distinct set of attributes. They can have some common attributes, but they have to have at least one attribute that is distinct to the user type or role. (3 user models for graduate students)" },
    { type: "li", depth: 0, text: "At least one one to many relationship between domain objects, or between users, or between users and domain objects - for instance, a movie has a one to many relation with actors, e.g., one movie has many actors. You can decide whether the schemas are embedded or not. (2 one to many relations for graduate students)" },
    { type: "li", depth: 0, text: "At least one many to many relationship between domain objects, or between users, or between users and domain objects - create a schema that can map several records in different tables or collections. (2 many to many for graduate students)" },
    { type: "h", level: 2, text: "UML Class Diagram and Data Model" },
    { type: "p", text: "Using Lucidchart\u00a0for Google Docs or your favorite UML editor, create a UML class diagram and make it available in a wiki page of the git repository. Call the wiki page Design. The class diagram should include at least 5 classes and their relations. Refer to the sample UML diagram for guidance. Here's a generic UML diagram capturing the user, domain objects, and their relationships. Use this as a guide to create your own UML diagram" },
    { type: "img", src: "/project/open-ended/02.png", alt: "Sample UML class diagram with users, domain objects, and relationships.", width: 1224, height: 926 },
    { type: "p", text: "Here are a couple more generic UML diagram capturing the user, domain objects, and several types of relationships. Use this as a guide to create your own data model" },
    { type: "img", src: "/project/open-ended/03.png", alt: "Generic UML diagram of users, domain objects, and several relationship types.", width: 780, height: 529 },
    { type: "p", text: "Here are a couple more examples data models. Click to expand." },
    { type: "img", src: "/project/open-ended/04.png", alt: "Example seller and buyer data model.", width: 813, height: 455 },
    { type: "img", src: "/project/open-ended/05.png", alt: "Example student and faculty data model.", width: 962, height: 358 },
    { type: "img", src: "/project/open-ended/06.png", alt: "Example art gallery data model.", width: 902, height: 655 },
    { type: "h", level: 2, text: "External Web API requirements" },
    { type: "p", text: "Create an interface to an external Web API such as Google maps, IMDB, YouTube, Yelp, Yahoo, Weather Channel, Yumly, Bestbuy, Amazon. The API should allow users to search for content, bookmark content, and retrieve details for a particular content element. If the API allows storing data, and relations between data, then the local database implementation is optional. If the API only allows read only operations, then the local database implementation is required. For instance, LinkedIn and other social network APIs allow registering, login, creating posts, view friends, upload photos, follow friends, search. If you implement most of these features, then the local database implementation is optional. If instead you are only using the Web API to do read only operations, then you must also implement the local database to store information about the search results locally in your database. Discuss the use of Web APIs with your instructor. A good place to start is at programmableweb.com" },
    { type: "p", text: "Field Validation" },
    { type: "p", text: "Cant update username" },
    { type: "p", text: "Login without email" },
    { type: "p", text: "Logout" },
    { type: "p", text: "Maintain session" },
    { type: "p", text: "Password must not be seen, unless requested" },
    { type: "p", text: "No dead ends" },
  ],
} as const satisfies ProjectDoc;
