import type { ProjectDoc } from "../types";

export const pazzaDoc = {
  slug: "pazza",
  title: "Kambaz Pazza",
  subtitle: "Final Project Requirements",
  description: "Integrate Pazza, a course Q&A forum, into Kambaz with posts, answers, folders, and a full-stack path.",
  blocks: [
    { type: "h", level: 1, text: "Introduction" },
    { type: "p", text: "In this Web development course, your final project will culminate in an exciting challenge: creating Pazza, a clone of a popular Q&A platform of a similar name. Pazza\u00a0will be\u00a0integrated directly into the ongoing Kambaz\u00a0project you've been developing throughout the semester. This project will test your skills in the MERN stack - MongoDB, Express.js, React, and Node.js - providing you with practical experience in merging new functionalities into existing systems. You'll need to replicate Pazza's core features such as posting questions, answering, and categorizing discussions, all while ensuring seamless integration with your current codebase. This task will enhance your ability to manage larger codebases, practice full-stack development, and understand the complexities of feature integration in a live, evolving project. Let's dive in and transform your semester-long project into a more interactive and community-driven platform!" },
    { type: "p", text: "The screenshot below illustrates Pazza\u00a0embedded in Kambaz. Clicking Pazza\u00a0in the Courses Navigation\u00a0sidebar displays Pazza\u00a0on the right hand side. Each course has its own separate instance of Pazza\u00a0with its own set of posts, questions, and answers. In its header at the top, Pazza\u00a0displays the name of the current course and the name of the currently logged in user." },
    { type: "img", src: "/project/pazza/01.png", alt: "Pazza Q&A embedded in Kambaz, with course navigation on the left and Pazza on the right.", width: 2034, height: 845 },
    { type: "h", level: 1, text: "Questions and Answers Screen (Q&AS)" },
    { type: "p", text: "Let's delve into the specifics of the Questions and Answers Screen (Q&AS)\u00a0for our Pazza project, which forms a crucial part of your final web development assignment. When you click on Pazza\u00a0in the Courses Navigation Sidebar (CNS), the Q&AS\u00a0is immediately revealed, serving as the default screen for Pazza. This screen is designed to facilitate interaction and learning by allowing users to post queries, contribute answers, and engage in discussions. Here's what you need to know about its structure: At the top of all screens within Pazza, there's a fixed Pazza Navigation Bar (PNB), which remains stationary as you scroll through the content, ensuring that navigation controls are always accessible. This bar includes several key elements essential for navigating and interacting with the platform. Let's explore these components and the layout of the Q&AS\u00a0to understand how they integrate to enhance user experience." },
    { type: "li", depth: 0, text: "When you click Pazza\u00a0in the Courses Navigation Sidebar\u00a0(CNS), the Questions and Answers Screen\u00a0(Q&AS) is revealed, as shown below" },
    { type: "li", depth: 0, text: "The Q&AS\u00a0is the default screen when Pazza\u00a0is clicked in the CNS" },
    { type: "img", src: "/project/pazza/02.png", alt: "Pazza Questions and Answers screen showing the navigation bar, folder filters, post list, and post pane.", width: 1877, height: 1366 },
    { type: "li", depth: 0, text: "The Q&AS\u00a0has the following sections" },
    { type: "img", src: "/project/pazza/03.png", alt: "Labeled sections of the Pazza Q&A layout: navigation bar, folder filters, list of posts, and post screen.", width: 1702, height: 84 },
    { type: "li", depth: 1, text: "At the top of all screens there is a fixed Pazza Navigation Bar\u00a0(PNB) that does not scroll with the rest of the content, is shown at all times, and has the following elements" },
    { type: "li", depth: 2, text: "Application Logo\u00a0(AL) on the left (pazza)" },
    { type: "li", depth: 2, text: "Course Name\u00a0(CN) showing the name (or course number) of the current course selected in the Kambaz Dashboard\u00a0(KD)" },
    { type: "li", depth: 3, text: "Each course has its own instance of Pazza, e.g., selecting a different course in the Kambaz Dashboard\u00a0(KD) would show a different set of questions, answers, users, folders, etc." },
    { type: "li", depth: 3, text: "Ignore the chevron to the right of the course name (the small triangle next to the course number)" },
    { type: "li", depth: 2, text: "After the CN, there the following tabs that highlight when the corresponding screen is displayed, e.g., underlined, bolded or different colors" },
    { type: "li", depth: 3, text: "Q&A\u00a0to navigate to Q&AS\u00a0described in this section and is the default screen when Pazza\u00a0is clicked" },
    { type: "li", depth: 3, text: "Resources\u00a0not required" },
    { type: "li", depth: 3, text: "Statistics\u00a0not required" },
    { type: "li", depth: 3, text: "Manage Class\u00a0to navigate to the Manage Class Screen\u00a0(MCS) described later in this document" },
    { type: "li", depth: 3, text: "Jose Annunziato\u00a0shows me as the currently logged in user. Display the name of the actual current logged in user" },
    { type: "li", depth: 4, text: "Pazza\u00a0behaves differently based on the currently logged in user, e.g., users's role such as instructors or student allow doing certain things, the posts that are visible are based on who is logged in" },
    { type: "li", depth: 3, text: "Ignore the rest of the options in the navigation bar" },
    { type: "img", src: "/project/pazza/04.png", alt: "Pazza navigation bar with logo, course name, Q&A, Resources, Statistics, Manage Class, and the current user.", width: 1698, height: 142 },
    { type: "li", depth: 0, text: "Below the Pazza Navigation Bar\u00a0(PNB), there's another fixed Folder Filters\u00a0(FF) listing various folders and buttons to filter the questions, notes, and answers posted by students and instructors" },
    { type: "li", depth: 1, text: "Live Q&A\u00a0not required" },
    { type: "li", depth: 1, text: "Drafts\u00a0not required" },
    { type: "li", depth: 1, text: "hw1, hw2, ..., office_hours\u00a0allow filtering posts by the folder they were created in" },
    { type: "li", depth: 2, text: "Users can select only one folder at a time" },
    { type: "li", depth: 2, text: "Posts listed in the List of Posts\u00a0are filtered by the selected filter" },
    { type: "li", depth: 2, text: "The selected folder is highlighted, e.g., underlined, bolded, or different color" },
    { type: "li", depth: 0, text: "Below the Folder Filters\u00a0(FF), there are two columns described in the following section" },
    { type: "li", depth: 2, text: "On the left of the Q&AS, there's the List of Posts Sidebar\u00a0(LOPS) shown here on the right" },
    { type: "li", depth: 2, text: "On the right of the Q&AS, there's the Post Screen\u00a0(PS)" },
    { type: "img", src: "/project/pazza/05.png", alt: "List of Posts sidebar with New Post, search, and posts grouped by date.", width: 684, height: 1228 },
    { type: "h", level: 2, text: "List of Posts Sidebar" },
    { type: "p", text: "On the left of the Q&AS, there's the List of Posts Sidebar\u00a0(LOPS) shown here on the right" },
    { type: "li", depth: 0, text: "At the top of the LOPS\u00a0there's a set of List of Posts Controls\u00a0(LOPC) including Unread, Updated, Unresolved, and Following. These are not required" },
    { type: "li", depth: 1, text: "To the left of Unread\u00a0there's the Toggle List of Posts Sidebar\u00a0button (TLOPS) represented as a triangle pointing to the left, and this button IS required" },
    { type: "li", depth: 1, text: "Clicking the TLOPS\u00a0hides and shows the List of Posts Sidebar" },
    { type: "li", depth: 1, text: "When the LOPS\u00a0is hidden, the TLOPS\u00a0triangle points to the right" },
    { type: "li", depth: 1, text: "When the LOPS\u00a0is shown, the TLOPS\u00a0triangle points to the left" },
    { type: "li", depth: 0, text: "Below the LOPC, there's a New Post Button\u00a0(NPB) and the Search Posts Field\u00a0(SPF)" },
    { type: "li", depth: 1, text: "Click on NPB\u00a0to reveal New Post Screen\u00a0(NPS), described later in this document" },
    { type: "li", depth: 1, text: "Type in the SPF\u00a0to filter posts listed in the List of Posts\u00a0(LOP) based on the text in the SPF" },
    { type: "li", depth: 1, text: "Show Actions\u00a0is not required" },
    { type: "li", depth: 0, text: "Below the NPB\u00a0and SPF\u00a0there's the List of Posts\u00a0(LOP)" },
    { type: "li", depth: 1, text: "The LOP\u00a0lists posts visible by the currently logged in user" },
    { type: "li", depth: 1, text: "Posts are listed in reverse chronological order with newer posts at the top of the list and older posts at the bottom of the list" },
    { type: "li", depth: 1, text: "Posts display" },
    { type: "li", depth: 2, text: "The title or summary in bold" },
    { type: "li", depth: 2, text: "Whether the post was created by a student or instructor" },
    { type: "li", depth: 2, text: "The text of the first 1 to 4 lines of the post" },
    { type: "li", depth: 2, text: "The time the post was created" },
    { type: "li", depth: 2, text: "Not required:" },
    { type: "li", depth: 3, text: "An icon if the post is a note and another icon if the post is a question" },
    { type: "li", depth: 3, text: "The message on whether the post is good or not" },
    { type: "li", depth: 1, text: "Posts are grouped in a category accordion\u00a0that hide or show the group of posts when clicked" },
    { type: "li", depth: 2, text: "Pinned\u00a0is not required" },
    { type: "li", depth: 2, text: "Today\u00a0lists the posts created today" },
    { type: "li", depth: 2, text: "Yesterday\u00a0lists the posts created yesterday" },
    { type: "li", depth: 2, text: "Last Week\u00a0lists the posts created last week" },
    { type: "li", depth: 2, text: "Additional category accordions\u00a0list posts grouped by what week they were posted in" },
    { type: "li", depth: 3, text: "The name of the category should be Monday's Date of Week - Sunday's Date of Week, e.g., if a week starts on Monday January 7, then the name of the category would be 1/7 - 1/13" },
    { type: "li", depth: 3, text: "You are free to make Sunday the first day of the week" },
    { type: "li", depth: 3, text: "The year is optional" },
    { type: "h", level: 2, text: "Post Screen" },
    { type: "p", text: "On the right of the Q&AS, there's the Post Screen\u00a0(PS) which is the main content and can display various screen depending on whether the user is viewing an existing post, answering a post or creating a new post. First let's discuss how users post new questions or notes." },
    { type: "img", src: "/project/pazza/06.png", alt: "New Post screen for a question, including Post To, folders, summary, and details.", width: 1874, height: 1257 },
    { type: "h", level: 3, text: "Posting New Questions or Notes" },
    { type: "p", text: "Let's now focus on the section detailing the requirements for the screen where users can post both questions and notes, an integral feature of the Pazza\u00a0platform. This screen allows users to contribute their queries and insights directly related to their courses. Here's an introduction to how this functionality works: Clicking New Post\u00a0in the Questions and Answers Screen (Q&AS)\u00a0will display the New Post Screen (NPS), where the process of creating and categorizing a post begins. At the top of this screen, you'll find three Post Type Tabs (PTT)\u00a0that let you specify whether your post is a Question, a Note, or a Poll/In-Class Response, although the latter is not required for this implementation. Here's a detailed look at the requirements for this screen:" },
    { type: "li", depth: 0, text: "Clicking New Post\u00a0in the Questions & Answers Screen\u00a0(Q&AS) displays the New Post Screen\u00a0(NPS) as shown above" },
    { type: "img", src: "/project/pazza/07.png", alt: "New Post control on the Questions and Answers screen.", width: 1037, height: 115 },
    { type: "li", depth: 0, text: "At the top of the NPS\u00a0there are three Post Type Tabs\u00a0(PTT)" },
    { type: "li", depth: 1, text: "Question\u00a0selects the type of this post as a Question\u00a0(selected by default)" },
    { type: "li", depth: 1, text: "Note\u00a0selects the type of this post as a Note" },
    { type: "img", src: "/project/pazza/08.png", alt: "Post type tabs for Question, Note, and Poll or In-Class Response.", width: 1031, height: 59 },
    { type: "li", depth: 1, text: "Poll/In-Class Response\u00a0is not required" },
    { type: "li", depth: 0, text: "Below the PTT, authors can select who to Post To\u00a0(PT)" },
    { type: "li", depth: 1, text: "Entire Class\u00a0selects that the post will be visible to everyone in the class (selected by default)" },
    { type: "li", depth: 1, text: "Individual Students/Instructors\u00a0selects that the post will only be visible to selected users" },
    { type: "li", depth: 2, text: "A user selection control appears allowing selecting which users can see the post" },
    { type: "li", depth: 2, text: "The first option is Instructors" },
    { type: "li", depth: 2, text: "The rest of the options are all users in the course including all students and instructors" },
    { type: "li", depth: 2, text: "You can select any number of users" },
    { type: "li", depth: 2, text: "Only users selected will be see the post in their LOP" },
    { type: "img", src: "/project/pazza/09.png", alt: "Post To choices for Entire Class or Individual Students/Instructors.", width: 1189, height: 115 },
    { type: "li", depth: 2, text: "No screen shot is provided, so you are free to implement as you wish" },
    { type: "li", depth: 0, text: "Below the PT, you can Select Folders\u00a0(SF)" },
    { type: "li", depth: 1, text: "Displaying the Folder(s) this post belongs to" },
    { type: "li", depth: 1, text: "The list of folders can be edited as described in the Manage Class\u00a0later in this document" },
    { type: "li", depth: 1, text: "You can select as many folders as you like" },
    { type: "li", depth: 1, text: "At least one folder is required" },
    { type: "li", depth: 1, text: "In the Q&AS, users can filter the posts in their LOP\u00a0by clicking the Folders" },
    { type: "img", src: "/project/pazza/10.png", alt: "Select Folders row on the New Post screen.", width: 1238, height: 85 },
    { type: "li", depth: 1, text: "Clicking Manage and reorder folders\u00a0navigates to Manage Folders\u00a0described later in this document" },
    { type: "li", depth: 0, text: "Below the SF, authors type a Summary\u00a0of the question" },
    { type: "li", depth: 1, text: "Serves as title and a quick one line short description of the Question\u00a0or Note" },
    { type: "li", depth: 1, text: "Maximum 100 characters" },
    { type: "img", src: "/project/pazza/11.png", alt: "Summary field on the New Post screen, limited to 100 characters.", width: 1304, height: 761 },
    { type: "li", depth: 1, text: "Summary\u00a0is required" },
    { type: "li", depth: 0, text: "Below the Summary, authors can type the Details\u00a0of their Question\u00a0or Note" },
    { type: "li", depth: 1, text: "Only support Rich Text Editor\u00a0(RTE). Search for, install, and use an existing RTE\u00a0React component" },
    { type: "li", depth: 1, text: "Details\u00a0is required" },
    { type: "li", depth: 1, text: "Ignore Plain Text Editor, Markdown Editor, and preview" },
    { type: "li", depth: 0, text: "Below the Details\u00a0ignore Posting Options" },
    { type: "li", depth: 1, text: "It is not required that posts be emailed to users" },
    { type: "li", depth: 1, text: "Posts can be viewed by coming to Pazza" },
    { type: "li", depth: 0, text: "Users click on Post My Question\u00a0or Post My Note\u00a0to create the post" },
    { type: "li", depth: 1, text: "Save Draft\u00a0is not required" },
    { type: "li", depth: 1, text: "Cancel\u00a0discards the post, closes the Post Screen\u00a0(PS) and returns to the Class at a Glance Screen\u00a0(CGS) described later in this document" },
    { type: "li", depth: 1, text: "If required fields are missing, show an appropriate alert, dialog or message below each required field" },
    { type: "li", depth: 1, text: "If no errors" },
    { type: "li", depth: 2, text: "Creates new Question\u00a0or Note" },
    { type: "li", depth: 2, text: "Shows new post in LOP" },
    { type: "li", depth: 2, text: "Highlights new post" },
    { type: "li", depth: 2, text: "Shows new post on the right side as described in the next section" },
    { type: "img", src: "/project/pazza/12.png", alt: "A newly created Pazza question shown in the post list and post pane.", width: 1123, height: 1329 },
    { type: "h", level: 3, text: "Viewing and Replying to Posts" },
    { type: "p", text: "Now, let's explore the requirements for the screen where users can view and post answers to questions within the Pazza\u00a0platform. This screen allows instructors and students to provide responses to queries posted by other students. Upon clicking a post in the List of Posts (LOP), it is displayed in the Post Screen (PS)\u00a0as shown in the provided screenshot. Here, the original question is prominently displayed at the top of the PS, with its summary highlighted as a bold header for easy reference. Below is a detailed list of requirements that define how this screen should function, ensuring a seamless and effective interaction for answering questions. If a post is selected, or a user clicks on a post to select it in the List of Posts\u00a0(LOP), then on the right hand side" },
    { type: "li", depth: 0, text: "The post is displayed in the PS\u00a0as shown here on the right" },
    { type: "li", depth: 0, text: "The current post is highlighted in the LOP" },
    { type: "li", depth: 0, text: "All posts displayed in the PS\u00a0display the following" },
    { type: "li", depth: 1, text: "How many have viewed the posts" },
    { type: "li", depth: 1, text: "The folder the post was created in" },
    { type: "li", depth: 1, text: "Who created the post" },
    { type: "li", depth: 1, text: "Edit\u00a0button that allow instructors and the author of the post to edit the post" },
    { type: "li", depth: 1, text: "Actions\u00a0dropdown only visible to instructors and author to Edit\u00a0or Delete\u00a0the post" },
    { type: "li", depth: 1, text: "Not required:" },
    { type: "li", depth: 2, text: "Anonymous posting is not allowed/required" },
    { type: "li", depth: 2, text: "Time past since last modified" },
    { type: "li", depth: 2, text: "Follow/Stop following" },
    { type: "li", depth: 2, text: "Good Question/Good Answer" },
    { type: "li", depth: 0, text: "If the post is a Question\u00a0(instead of a Note)" },
    { type: "li", depth: 1, text: "Below the post, in a section labeled Student's Answers, display all answers from students (if any) including" },
    { type: "li", depth: 2, text: "Author of the answer" },
    { type: "li", depth: 2, text: "Timestamp of the answer" },
    { type: "li", depth: 2, text: "Edit\u00a0button for instructors and author to edit the answer" },
    { type: "li", depth: 2, text: "Action\u00a0dropdown allowing instructors and author to Edit\u00a0or Delete\u00a0the answer" },
    { type: "li", depth: 2, text: "If the question has not been answered, and the current user is a student, then the student can post an answer in a WYSIWYG\u00a0editor" },
    { type: "li", depth: 1, text: "Below the student answers (if any), in a section labeled Instructor's Answers, display answers from instructors (if any) including" },
    { type: "li", depth: 2, text: "Author of the answer" },
    { type: "li", depth: 2, text: "Timestamp of the answer" },
    { type: "li", depth: 2, text: "Edit\u00a0button for instructors to edit the answer" },
    { type: "li", depth: 2, text: "Action\u00a0dropdown allowing instructors to Edit\u00a0or Delete\u00a0the answer" },
    { type: "li", depth: 2, text: "If the question has not been answered, and the current user is an instructor, then the instructor can post an answer in a WYSIWYG\u00a0editor" },
    { type: "img", src: "/project/pazza/13.png", alt: "Viewing a question with student answers, instructor answers, and follow-up discussion.", width: 1346, height: 892 },
    { type: "li", depth: 0, text: "Follow up Discussion\u00a0(FUD)" },
    { type: "li", depth: 1, text: "Under the answers (if any), FUD\u00a0allows participants to enter a discussions with nested replies as shown here on the right" },
    { type: "li", depth: 1, text: "Start a new followup discussion\u00a0field or textarea to start a new discussion" },
    { type: "li", depth: 1, text: "All discussions have" },
    { type: "li", depth: 2, text: "Resolved\u00a0and Unresolved\u00a0buttons to toggle on whether the discussion has been resolved" },
    { type: "li", depth: 2, text: "Author of the discussion" },
    { type: "li", depth: 2, text: "Timestamp of when the discussion started" },
    { type: "li", depth: 2, text: "The text of the discussion" },
    { type: "li", depth: 2, text: "Action\u00a0dropdown allowing instructors and author to Edit\u00a0or Delete\u00a0the discussion" },
    { type: "li", depth: 2, text: "Helpful\u00a0is not required" },
    { type: "li", depth: 2, text: "A Reply\u00a0field or textarea allowing to reply to the discussion" },
    { type: "li", depth: 2, text: "Replies\u00a0that contain" },
    { type: "li", depth: 3, text: "Author of the reply" },
    { type: "li", depth: 3, text: "Timestamp of the reply" },
    { type: "li", depth: 3, text: "Text of the reply" },
    { type: "li", depth: 3, text: "Action\u00a0dropdown allowing instructors and author to Edit\u00a0or Delete\u00a0the reply" },
    { type: "li", depth: 3, text: "Good comment\u00a0is not required" },
    { type: "li", depth: 3, text: "A Reply\u00a0field or textarea allowing to reply to the reply" },
    { type: "img", src: "/project/pazza/14.png", alt: "Follow-up discussion with nested replies under a Pazza post.", width: 1201, height: 399 },
    { type: "h", level: 3, text: "Class at a Glance Screen" },
    { type: "p", text: "If no post is selected the PS\u00a0displays Class at a Glance Screen\u00a0(CGS) displaying the following meta information as shown here on the right" },
    { type: "li", depth: 0, text: "Number of unread posts or no unread posts" },
    { type: "li", depth: 0, text: "Number of unanswered posts or no unanswered posts" },
    { type: "li", depth: 0, text: "Total number of posts" },
    { type: "li", depth: 0, text: "Number of instructor responses" },
    { type: "li", depth: 0, text: "Number of student responses" },
    { type: "li", depth: 0, text: "Number of students enrolled" },
    { type: "li", depth: 0, text: "Ignore everything else in the screen" },
    { type: "li", depth: 0, text: "Not required:" },
    { type: "li", depth: 1, text: "Number of unanswered followups" },
    { type: "li", depth: 1, text: "Total contributions" },
    { type: "li", depth: 1, text: "Average time of response time in hours" },
    { type: "img", src: "/project/pazza/15.png", alt: "Class at a Glance counts for unread, unanswered, and total posts.", width: 1642, height: 192 },
    { type: "h", level: 1, text: "Manage Class Screen (MCS)" },
    { type: "li", depth: 0, text: "Clicking Manage Class Tab\u00a0(MCT) reveals the the Manage Class Screen\u00a0(MCS) as shown here on the right" },
    { type: "li", depth: 1, text: "Only instructors can see and click the MCT" },
    { type: "li", depth: 1, text: "Only instructors can navigate to the MCS, e.g., the URL or hash to MCS\u00a0is protected" },
    { type: "li", depth: 0, text: "The MCS\u00a0shows 7 tabs of which you must implement the following" },
    { type: "li", depth: 1, text: "Manage Folders Tab\u00a0(MFT)" },
    { type: "li", depth: 2, text: "Clicking the MFT\u00a0reveals the Manage Folder Screen\u00a0(MFS) described later in this document" },
    { type: "img", src: "/project/pazza/16.png", alt: "Manage Class screen with the Manage Folders tab and the default folder list.", width: 1706, height: 1410 },
    { type: "h", level: 2, text: "Manage Folders Screen (MFS)" },
    { type: "li", depth: 0, text: "Clicking the MFT\u00a0reveals the Manage Folders Screen\u00a0(MFS) as shown here on the right" },
    { type: "li", depth: 0, text: "The blue description box on the left is not required" },
    { type: "li", depth: 0, text: "Descriptions and other labels and text can be customized at your discretion" },
    { type: "li", depth: 0, text: "The title can be one of the following" },
    { type: "li", depth: 1, text: "Configure Class Folders\u00a0as shown" },
    { type: "li", depth: 1, text: "Manage Folders" },
    { type: "li", depth: 0, text: "The default folders are as shown here on the right, e.g., hw1, hw2, hw3, ..., project, exam, logistics, other, office_hours" },
    { type: "li", depth: 0, text: "To add a new folder, instructors type the name of the new folder in a field and click Add Folder" },
    { type: "li", depth: 1, text: "The screenshot suggests you can add multiple folders at once, but it is not required. You are only required to be able to add one folder at a time" },
    { type: "li", depth: 1, text: "The list of folders updates immediately after adding a new folder, and list persists if screen is refreshed" },
    { type: "li", depth: 0, text: "To delete folders select folders to be deleted and click on Delete selected folders" },
    { type: "li", depth: 0, text: "To edit the name of a folder" },
    { type: "li", depth: 1, text: "Click Edit\u00a0next to the folder to be edited" },
    { type: "li", depth: 1, text: "Folder name is replaced by an input field" },
    { type: "li", depth: 1, text: "Edit\u00a0button is replaced by buttons Save, and Cancel" },
    { type: "li", depth: 1, text: "Clicking Save\u00a0replaces Save\u00a0and Cancel\u00a0buttons with Edit\u00a0and input field is replaced with the new folder name" },
    { type: "li", depth: 1, text: "Clicking Cancel\u00a0replaces Save\u00a0and Cancel\u00a0buttons with Edit\u00a0and input field is replaced with original folder name" },
    { type: "li", depth: 0, text: "Not required:" },
    { type: "li", depth: 1, text: "Disable folders" },
    { type: "li", depth: 1, text: "Create subfolders" },
    { type: "li", depth: 1, text: "Numbered; suffix" },
    { type: "li", depth: 1, text: "Hide all subfolders" },
    { type: "li", depth: 1, text: "Rearranging order of folders" },
    { type: "h", level: 1, text: "General Requirements" },
    { type: "li", depth: 0, text: "All fields must be clearly labeled. Use the label in the screenshots unless otherwise stated" },
    { type: "li", depth: 1, text: "Additional descriptive text explaining a particular field or feature is optional" },
    { type: "li", depth: 1, text: "Add placeholders on input fields and textareas as shown" },
    { type: "li", depth: 1, text: "You can reuse text as provided in the screenshots or create your own" },
    { type: "li", depth: 0, text: "The type of the input field must be appropriate for the type of information being requested. For example" },
    { type: "li", depth: 1, text: "Input type date - used to request a date" },
    { type: "li", depth: 1, text: "Input type number - used to request a numeric value" },
    { type: "li", depth: 1, text: "Input type email - used to request an email" },
    { type: "li", depth: 1, text: "Textarea - used to request long form text" },
    { type: "li", depth: 1, text: "Single select dropdowns or radio buttons - used to request single option" },
    { type: "li", depth: 1, text: "Multiple select dropdowns or check box buttons - used to request multiple options" },
    { type: "li", depth: 0, text: "Look and feel does not have to match the screen shots provided, but must capture the intended feature. For instance" },
    { type: "li", depth: 0, text: "Any field or feature not explicitly described in this document is not required, but feel free to implement at your discretion" },
    { type: "li", depth: 0, text: "If a tab or folder or post is currently selected, they must be highlighted to signify that they are selected. This can be done by underlining the text, or bolding the text, or changing the foreground and/or background color" },
    { type: "li", depth: 0, text: "All settings, selections, and data is persisted and re-rendered for user feedback, e.g., if an instructor adds folders in Manage Folders, logs out, and then logs back in, then the new folders are still there. If a student answered a question or replied to a followup, if they logout, and then log back in, if they visit the same question, they can see the answers and replies they created." },
  ],
} as const satisfies ProjectDoc;
