import type { ProjectDoc } from "../types";

export const quizzesDoc = {
  slug: "quizzes",
  title: "Kambaz Quizzes",
  subtitle: "Final Project Requirements",
  description: "Extend Kambaz with a Quizzes section: faculty create and publish quizzes; students take them and review results.",
  blocks: [
    { type: "p", text: "Throughout this semester, we have been exploring various web development technologies, learning the fundamental tools and techniques that bring dynamic and interactive Web applications to life. To practice your development skills, you have been building Kambaz, our class's own version of a learning management system (LMS), inspired by a popular LMS. As we approach the culmination of our course, it's time to challenge yourselves further and extend Kambaz by developing a Quizzes\u00a0section. This new feature will be a cornerstone of the Kambaz system, facilitating an interactive learning experience and enabling assessment to be seamlessly integrated into the online learning environment." },
    { type: "img", src: "/project/quizzes/01.png", alt: "Northeastern myNortheastern username and password login form with a red Log In button.", width: 584, height: 616 },
    { type: "h", level: 1, text: "Authentication and Authorization" },
    { type: "p", text: "As part of the assignments we have implemented user authentication allowing multiple users to login simultaneously into the Kambaz\u00a0application. Your implementation of the Quizzes must include support for multiple and simultaneous user signup, signin, and profile. Additionally you need to support two types of users: Faculty and Students. As a Faculty, a user can create, edit, preview, and delete quizzes. As a Student, a user can only view the list of quizzes, take a quiz, and view the final grade of the quiz. To simplify configuring a user's role, you can provide a checkbox or dropdown users can choose when signing up." },
    { type: "h", level: 1, text: "Courses per User" },
    { type: "p", text: "When a user logs in, they should only see the courses they are associated with. For instance, in the Dashboard faculty should only see the courses they have created and students should only see the courses they are enrolled in. In the assignments we implemented the signin and course creation process so associating courses with the currently logged in user should be simple. For students, you'll need to create a mechanism for them to enroll into a course. One suggestion would be that their Dashboard is initially empty since they are not enrolled in any course, but they can click on some link that would take them to a list of all the courses available from which they can choose which courses they want to enroll in. Then back in their Dashboard, they would only see the courses they are enrolled in. Clicking the course from the Dashboard\u00a0takes a user to the Home\u00a0screen of the course. Faculty can edit the content in a course, but students can not." },
    { type: "h", level: 1, text: "Quiz List Screen" },
    { type: "p", text: "Implement a Quizzes\u00a0screen that display a list of quizzes as shown below. The Quizzes\u00a0screen displays the quizzes for the current course. If a user navigates to a different course from the Dashboard, they would see a different list of quizzes." },
    { type: "h", level: 2, text: "Quizzes screen Requirements" },
    { type: "li", depth: 0, text: "Displays list of quizzes" },
    { type: "li", depth: 0, text: "Empty by default. Provide message to click Add Quiz\u00a0button (+ Quiz)" },
    { type: "img", src: "/project/quizzes/02.png", alt: "Canvas-style Quizzes list for a course, with quiz titles, availability, due dates, points, question counts, and a + Quiz control.", width: 1956, height: 1550 },
    { type: "li", depth: 0, text: "Clicking Add Quiz\u00a0button (+ Quiz) creates a new quiz with a default name and navigates to Quiz Details\u00a0screen for editing the quiz. Alternatively, it can navigate to Quiz Details Editor\u00a0screen shown later in this document" },
    { type: "li", depth: 0, text: "Clicking the context menu button (3 dots) reveals the Quiz Context Menu with options" },
    { type: "li", depth: 1, text: "Edit\u00a0- navigates to Quiz Details\u00a0screen" },
    { type: "li", depth: 1, text: "Delete\u00a0- removes the quiz and stays in the Quiz List\u00a0screen" },
    { type: "li", depth: 1, text: "Publish\u00a0- publishes the quiz and option becomes Unpublish\u00a0so you can unpublish" },
    { type: "li", depth: 1, text: "Sort\u00a0- allows sorting the course by name, due date, or available date" },
    { type: "li", depth: 1, text: "Copy\u00a0- allows copying the quiz to another course (optional)" },
    { type: "li", depth: 0, text: "By default quizzes are unpublished and unavailable to students depicted with a Unpublished\u00a0symbol \ud83d\udeabas shown below" },
    { type: "li", depth: 0, text: "Clicking Unpublished\u00a0symbol publishes the quiz, makes it available to students and is represented with the Published\u00a0symbol\u00a0\u2705as shown below" },
    { type: "li", depth: 0, text: "Clicking quiz title navigates to Quiz Details screen" },
    { type: "li", depth: 0, text: "Under the quiz title display" },
    { type: "li", depth: 1, text: "Availability" },
    { type: "li", depth: 2, text: "Closed\u00a0- if current date is after quizzes Available Date" },
    { type: "li", depth: 2, text: "Available\u00a0- if current date is between Available Date\u00a0and Available Until Date" },
    { type: "li", depth: 2, text: "Not available until <AVAILABLE DATE>\u00a0- if current date is before the Available Date" },
    { type: "li", depth: 1, text: "Due date\u00a0- as shown below" },
    { type: "li", depth: 1, text: "Points\u00a0- as shown below" },
    { type: "li", depth: 1, text: "Number of questions\u00a0- as shown below" },
    { type: "li", depth: 1, text: "Score\u00a0- if the current user is a student, the score from the last attempt is shown" },
    { type: "img", src: "/project/quizzes/03.png", alt: "Quiz list rows showing Closed, Available, and Not available until dates plus due date, points, and question counts.", width: 1528, height: 1182 },
    { type: "img", src: "/project/quizzes/04.png", alt: "Published quiz checkmark icon as shown on the quiz list.", width: 360, height: 128 },
    { type: "h", level: 1, text: "Quiz Details Screen" },
    { type: "p", text: "For faculty users, implement a Quizzes Details\u00a0screen as shown below with only following properties. For students, provide a button to start the quiz. Ignore other properties" },
    { type: "li", depth: 0, text: "Quiz Type\u00a0- Graded Quiz\u00a0(default), Practice Quiz, Graded Survey, Ungraded Survey" },
    { type: "li", depth: 0, text: "Points\u00a0- the sum of the points of all questions in the quiz" },
    { type: "li", depth: 0, text: "Assignment Group\u00a0- Quizzes\u00a0(default), Exams, Assignments, Project" },
    { type: "li", depth: 0, text: "Shuffle Answers\u00a0- Yes (default) / No" },
    { type: "li", depth: 0, text: "Time Limit\u00a0- 20 Minutes (default)" },
    { type: "li", depth: 0, text: "Multiple Attempts\u00a0- No (default) / Yes" },
    { type: "li", depth: 0, text: "How Many Attempts\u00a0- 1 (default). If Multiple Attempts\u00a0is Yes, then can configure how many times the student can retake the quiz" },
    { type: "li", depth: 0, text: "Show Correct Answers\u00a0- If and when correct answers are shown to students" },
    { type: "li", depth: 0, text: "Access Code\u00a0- Passcode students need to type to access the quiz. Default is blank" },
    { type: "li", depth: 0, text: "One Question at a Time\u00a0- Yes (default) / No" },
    { type: "li", depth: 0, text: "Webcam Required\u00a0- No (default) / Yes" },
    { type: "li", depth: 0, text: "Lock Questions After Answering\u00a0- No (default) / Yes" },
    { type: "li", depth: 0, text: "Due date\u00a0- date the assignment is due" },
    { type: "li", depth: 0, text: "Available date\u00a0- date assignment is available" },
    { type: "li", depth: 0, text: "Until date\u00a0- date assignment is available until" },
    { type: "h", level: 2, text: "Quizzes Details Screen Requirements" },
    { type: "li", depth: 0, text: "Displays summary of quiz properties" },
    { type: "li", depth: 0, text: "Click Preview\u00a0button to navigate to Quiz Preview\u00a0screen" },
    { type: "li", depth: 0, text: "Click Edit\u00a0to navigate to Quiz Editor\u00a0screen" },
    { type: "img", src: "/project/quizzes/05.png", alt: "Quiz Details screen summarizing quiz type, points, assignment group, shuffle, time limit, attempts, dates, and Preview and Edit actions.", width: 2048, height: 1613 },
    { type: "h", level: 1, text: "Quiz Details Editor screen" },
    { type: "p", text: "The Quiz Editor\u00a0screen allows faculty to edit the meta data for a quiz. Implement the Quiz Editor\u00a0screen as shown below. Feel free to give it your own twist" },
    { type: "li", depth: 0, text: "Has 2 tabs" },
    { type: "li", depth: 1, text: "Details (default)" },
    { type: "li", depth: 1, text: "Questions" },
    { type: "li", depth: 0, text: "Clicking Details\u00a0navigates to the Quiz Details Editor\u00a0screen" },
    { type: "li", depth: 0, text: "Clicking Questions\u00a0navigates to Quiz Questions Editor\u00a0screen" },
    { type: "img", src: "/project/quizzes/06.png", alt: "Quiz editor with Details and Questions tabs at the top of the form.", width: 958, height: 687 },
    { type: "li", depth: 0, text: "Can edit fields" },
    { type: "li", depth: 1, text: "Title\u00a0(input text)" },
    { type: "li", depth: 1, text: "Description\u00a0(WYSIWYG)" },
    { type: "li", depth: 1, text: "Assigned to\u00a0- Ignore" },
    { type: "li", depth: 1, text: "Quiz Type\u00a0- Graded Quiz\u00a0(default), Practice Quiz, Graded Survey, Ungraded Survey" },
    { type: "li", depth: 1, text: "Points\u00a0- the sum of the points of all questions in the quiz" },
    { type: "img", src: "/project/quizzes/07.png", alt: "Details tab selected in the quiz editor.", width: 179, height: 144 },
    { type: "img", src: "/project/quizzes/08.png", alt: "Questions tab selected in the quiz editor.", width: 187, height: 144 },
    { type: "li", depth: 1, text: "Assignment Group\u00a0- Quizzes\u00a0(default), Exams, Assignments, Project" },
    { type: "li", depth: 1, text: "Shuffle Answers\u00a0- Yes (default) / No" },
    { type: "li", depth: 1, text: "Time Limit\u00a0- 20 Minutes (default)" },
    { type: "li", depth: 1, text: "Multiple Attempts\u00a0- No (default) / Yes" },
    { type: "li", depth: 1, text: "Show Correct Answers\u00a0- If and when correct answers are shown to students" },
    { type: "li", depth: 1, text: "Access Code\u00a0- Passcode students need to type to access the quiz. Default is blank" },
    { type: "li", depth: 1, text: "One Question at a Time\u00a0- Yes (default) / No" },
    { type: "li", depth: 1, text: "Webcam Required\u00a0- No (default) / Yes" },
    { type: "li", depth: 1, text: "Lock Questions After Answering\u00a0- No (default) / Yes" },
    { type: "li", depth: 1, text: "Due date\u00a0- date the assignment is due" },
    { type: "li", depth: 1, text: "Available date\u00a0- date assignment is available" },
    { type: "li", depth: 1, text: "Until date\u00a0- date assignment is available until" },
    { type: "li", depth: 0, text: "Clicking Save\u00a0saves changes and navigates to Quiz Details\u00a0screen" },
    { type: "li", depth: 0, text: "Clicking Save and Publish\u00a0saves & publishes quiz and navigates to Quiz List\u00a0screen" },
    { type: "li", depth: 0, text: "Clicking Cancel\u00a0doesn\u2019t save and navigates ton Quiz List\u00a0screen" },
    { type: "img", src: "/project/quizzes/09.png", alt: "Quiz editor due, available, and until date fields with Save, Save and Publish, and Cancel.", width: 712, height: 450 },
    { type: "h", level: 1, text: "Quiz Questions Editor screen" },
    { type: "p", text: "Clicking Questions\u00a0tab navigates to Quiz questions screen with the following behavior" },
    { type: "li", depth: 0, text: "Displays list of questions for this quiz. List is initially empty" },
    { type: "li", depth: 0, text: "Clicking New Question\u00a0adds question at bottom of list. Multiple choice\u00a0question is default" },
    { type: "li", depth: 0, text: "New questions are displayed in edit preview mode by default" },
    { type: "li", depth: 0, text: "Clicking Edit\u00a0displays question in edit mode" },
    { type: "li", depth: 0, text: "Dropdown to choose question type" },
    { type: "li", depth: 0, text: "Points\u00a0shows sum of all the points of each question." },
    { type: "li", depth: 0, text: "Minimum question types:" },
    { type: "li", depth: 1, text: "True/false question" },
    { type: "li", depth: 1, text: "Multiple choice question" },
    { type: "li", depth: 1, text: "Fill in a blank question" },
    { type: "li", depth: 0, text: "Clicking Cancel\u00a0button dismisses the edits" },
    { type: "img", src: "/project/quizzes/10.png", alt: "Quiz Questions editor listing questions with a New Question control.", width: 1017, height: 1281 },
    { type: "li", depth: 0, text: "Clicking Save\u00a0saves the edits but does not publish the quiz" },
    { type: "p", text: "Here's an example of how Canvas\u00a0renders the Questions editor, but feel free to give it your own twist." },
    { type: "h", level: 2, text: "Multiple Choice Question Editor (default)" },
    { type: "p", text: "Implement a Multiple choice\u00a0type question where students need select one correct choice out a list of multiple choices. Faculty can configure the following question properties" },
    { type: "li", depth: 0, text: "Title (input:text) - the title of the question" },
    { type: "li", depth: 0, text: "Points (input:number) - how many points is the question" },
    { type: "li", depth: 0, text: "Question (WYSIWYG)" },
    { type: "li", depth: 0, text: "Choices (textarea) - multiple paragraphs of which only one is the correct choice. Faculty can add/remove any number of choices. Each choice has a radio button that selects it as the single correct answer." },
    { type: "li", depth: 0, text: "Cancel button discards changes" },
    { type: "li", depth: 0, text: "Save/Update Question button saves question" },
    { type: "p", text: "Here's an example of how Canvas renders the Multiple choice question\u00a0editor, but feel free to give it your own twist" },
    { type: "img", src: "/project/quizzes/11.png", alt: "Canvas-style multiple choice question editor with title, points, question body, and choices.", width: 1045, height: 840 },
    { type: "h", level: 2, text: "True/False Question Editor" },
    { type: "p", text: "Implement a True false\u00a0type question where students need select whether a text is true or false. Faculty can configure the following question properties" },
    { type: "li", depth: 0, text: "Title (input:text) - the title of the question" },
    { type: "li", depth: 0, text: "Points (input:number) - how many points is the question" },
    { type: "li", depth: 0, text: "Question (WYSIWYG)" },
    { type: "li", depth: 0, text: "Tue/false - whether the correct answer is true or false. Can be a simple checkbox or a couple of radio buttons." },
    { type: "img", src: "/project/quizzes/12.png", alt: "Canvas-style true/false question editor with title, points, question body, and True or False.", width: 1017, height: 1052 },
    { type: "li", depth: 0, text: "Cancel button discards changes" },
    { type: "li", depth: 0, text: "Save/Update Question\u00a0button saves question" },
    { type: "p", text: "Here's an example of how Canvas renders the True false question\u00a0editor, but feel free to give it your own twist" },
    { type: "h", level: 2, text: "Fill in the Blank Question Editor" },
    { type: "p", text: "Implement a Fill in the blank\u00a0type question where students need to fill in a blank and the answer is compared to various possibly correct answers. Faculty can configure the following question properties" },
    { type: "li", depth: 0, text: "Title (input:text) - the title of the question" },
    { type: "li", depth: 0, text: "Points (input:number) - how many points is the question" },
    { type: "li", depth: 0, text: "Question (WYSIWYG)" },
    { type: "img", src: "/project/quizzes/13.png", alt: "Canvas-style fill-in-the-blank question editor with possible correct answers for the blank.", width: 1520, height: 1974 },
    { type: "li", depth: 0, text: "Blank (input:text) - a list of possible correct answers for the blank. Faculty can add/remove any number of possible correct answers. Answers can be case insensitive" },
    { type: "li", depth: 0, text: "Cancel button discards changes" },
    { type: "li", depth: 0, text: "Save/Update Question button saves question" },
    { type: "p", text: "Here's an example of how Canvas renders the Fill in the blank question\u00a0editor, but feel free to give it your own twist" },
    { type: "h", level: 1, text: "Quiz Preview screen" },
    { type: "p", text: "The Quiz Preview\u00a0screen allow faculty to view the quiz as students would see the quiz. The faculty can answer the quiz and view the score they would get with the answers they provided. Like students, after the faculty completes a preview of the quiz, they can see what questions they got wrong and the final score. The answers from the faculty don't need to be stored in the database. Faculty can not edit the quiz while they are taking the quiz. To edit the quiz they can click on an Edit Quiz\u00a0button that navigates them to the Quiz Questions Editor screen\u00a0described earlier." },
    { type: "h", level: 1, text: "Persist Student Quiz Answers and Scores" },
    { type: "p", text: "Although faculty can edit and preview a quiz, a student can not edit a quiz, but can take the quiz as many times as configured in the How Many Attempts\u00a0property in the Quiz Details screen. The answers to the quiz are stored per student so that they can come back later and see the when they took the quiz, what score they got, and what they answered the last time they took the quiz. Questions are highlighted as green or checkmark if they were correctly answered, and red or X if they were answered incorrectly. Students can't change the answers of a quiz they already took. They can take the quiz again if Multiple Attempts\u00a0is configured and as many times as configured in How Many Attempts. Once a student has exhausted the number of attempts, they can not take the quiz again. Students can only see the answers and score to the last attempt. If another student takes the quiz, their answers are stored separately so that when they submit their answers and then comeback to view the results, they can see what they answered in their last attempt." },
  ],
} as const satisfies ProjectDoc;
